#!/usr/bin/env python3
"""Generate the `klt sim` startup-time requests for rcosc_top (issue #78).

Ratified row: "Startup time <= 10 us to within trimmed accuracy" (README.md
target-spec table; characterization report row 10).

This does NOT launch ngspice.  It writes a testbench netlist and one
`klt sim` request per supply value; the corner grid is expressed as a
`klt sim` corners request so the full factorial goes to the batch fleet
(KLT_SIM_BACKEND=batch), never as a hand-launched ngspice grid.

Corner definitions are imported from sim/pvt/pvt_sweep.py
(PROCESS_CORNERS, TEMPS_C, VDDS_V), not re-typed -- the same pattern
sim/iq/iq_sweep.py follows -- so campaigns cannot drift apart.  Each request
carries the process (7) x temperature (3) grid = 21 corners; the three
supplies are three requests (the supply is baked into the PWL ramp, and
`klt sim` refuses a supply_v `alter` on a PWL source), 63 points in all.

Stimulus (assumption, documented in sim/startup/README.md): VDD ramps
linearly 0 -> VDD over RAMP_NS (1 us) from t=0; the trim bits are tied to
the rail through the same ramp-following sources, i.e. trim code
0xA3 (the post-#60 calibration code) is held at every point.  The trim
pins follow VDD (logic-high = VDD) so the code is valid throughout the ramp.

Measurement: the clk and vdd waveforms are retained (options.waveforms,
save_mode "netlist" so only v(clk)/v(vdd) are saved) and
sim/startup/startup_report.py post-processes them.  In-deck `.meas` cards
give a cross-check (first clk edge time) that fails visibly if the clock
never toggles.

Usage:  python3 gen_requests.py [--out DIR]
        python3 gen_requests.py --probe tt:27:3.3   # one-corner request
"""
import argparse
import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
sys.path.insert(0, str(REPO / "sim" / "pvt"))
from pvt_sweep import PROCESS_CORNERS, TEMPS_C, VDDS_V  # noqa: E402

CODE = 0xA3
RAMP_NS = 1000
TSTOP_NS = 20000
TSTEP = "200p"
SRC = REPO / "design" / "netlist" / "pvt_tb.spice"


def write_dut() -> None:
    text = SRC.read_text().splitlines()
    start = next(i for i, l in enumerate(text) if "expanding" in l and "rcosc_top.sym" in l)
    end = next(i for i, l in enumerate(text) if l.strip() == ".end")
    block = [l for l in text[start:end] if not l.startswith(("** sym_path:", "** sch_path:"))]
    (HERE / "rcosc_top_schematic.spice").write_text(
        "* schematic DUT for the startup bench: pvt_tb.spice's embedded rcosc_top hierarchy\n"
        "* (generated by gen_requests.py; no device or connection edited)\n"
        + "\n".join(block) + "\n")


def write_tb(vdd: float) -> str:
    tag = f"v{int(round(vdd * 10)):02d}"
    r = RAMP_NS
    lines = [
        f"* rcosc_top startup bench, VDD ramp 0->{vdd:g} V in {r} ns, trim 0x{CODE:02X} (generated by gen_requests.py)",
        ".param sw_stat_global=0 sw_stat_mismatch=0 mc_skew=3 res_mc_skew=3 cap_mc_skew=3 fnoicor=0",
        '.include "rcosc_top_schematic.spice"',
        "XXDUT vdd 0 clk t0 t1 t2 t3 t4 t5 t6 t7 rcosc_top",
        f"VDD vdd 0 PWL(0 0 {r}n {vdd:g})",
    ]
    for i in range(8):
        if (CODE >> i) & 1:
            lines.append(f"VT{i} t{i} 0 PWL(0 0 {r}n {vdd:g})")
        else:
            lines.append(f"VT{i} t{i} 0 DC 0")
    lines.append(".save v(clk) v(vdd)")
    name = f"tb_{tag}.spice"
    (HERE / name).write_text("\n".join(lines) + "\n")
    return tag


def request(tag: str, vdd: float, procs, temps) -> dict:
    vmid = vdd / 2
    return {
        "netlist": f"tb_{tag}.spice",
        "engine": "ngspice",
        "netlist_source": "schematic",
        "models": {"pdk": "gf180mcuC", "lib": "libs.tech/ngspice/sm141064.ngspice"},
        "corners": {
            "process": [{"name": n, "sections": [PROCESS_CORNERS[n][0], PROCESS_CORNERS[n][1],
                                                 PROCESS_CORNERS[n][2], "cap_mim"]} for n in procs],
            "temperature_c": temps,
        },
        "analysis": {"kind": "tran", "args": f"{TSTEP} {TSTOP_NS}n"},
        "measurements": [
            {"name": "t_first_edge", "unit": "s",
             "spice": f".meas tran t_first_edge WHEN v(clk)={vmid:.4f} RISE=1"},
            {"name": "t_edge_50", "unit": "s",
             "spice": f".meas tran t_edge_50 WHEN v(clk)={vmid:.4f} RISE=50"},
        ],
        "batch": {"capacity_wait_s": 1200},
        "options": {"timeout_s": 1800, "keep_artifacts": True, "waveforms": True,
                    "save_mode": "netlist", "ngspice_init": ["set measureprec=8"]},
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--probe", help="proc:temp:vdd, e.g. tt:27:3.3 -> request_probe.json (one corner)")
    a = ap.parse_args()
    write_dut()
    if a.probe:
        p, t, v = a.probe.split(":")
        tag = write_tb(float(v))
        req = request(tag, float(v), [p], [float(t)])
        (HERE / "request_probe.json").write_text(json.dumps(req, indent=2) + "\n")
        return
    for v in VDDS_V:
        tag = write_tb(v)
        req = request(tag, v, list(PROCESS_CORNERS), TEMPS_C)
        (HERE / f"request_{tag}.json").write_text(json.dumps(req, indent=2) + "\n")


if __name__ == "__main__":
    main()
