#!/usr/bin/env python3
"""Generate the per-sample trim-selection Monte Carlo bench (issue #77).

Item-6 groundwork (DR-0019 section 2).  Writes, next to this script:

  tb_trimsel_nomm.spice       (DUT hierarchy from design/netlist/pvt_tb.spice inlined) bench with sw_stat_mismatch=0  (zero-mismatch control)
  tb_trimsel_mm.spice         bench with sw_stat_mismatch=1  (mismatch on)
  tb_fixedcode.spice          fixed-code reference (code decoded from one DC source)
  request_*.json              klt sim requests (see README.md for the run commands)

The bench does the DR-0019 per-die calibration INSIDE one ngspice session,
so every trim-code probe of a sample sees the same mismatch draw:

  1. a binary search over the 8-bit code (alter VT0..VT7, one transient per
     probe) for the code whose frequency is nearest the target at the
     calibration point (27 C, 3.3 V),
  2. the chosen code is held (VT0..VT7 left at it),
  3. its frequency and the residual vs target are exposed as `set` variables
     that klt sim harvests as `expr` measurements.

Mismatch parameters are drawn once when ngspice expands the netlist
(agauss in the model subcircuits), so they persist across `alter` + `tran`
re-runs within the session.  The search targets the ratified 48.000 MHz.

Run from this directory:  python3 gen_bench.py
"""
import json
from pathlib import Path

here = Path(__file__).parent
SRC = here.parent.parent / "design" / "netlist" / "pvt_tb.spice"
TARGET_HZ = 48.0e6
VDD = 3.3
VMID = VDD / 2
PROC = {
    "tt": ["typical", "res_typical", "mimcap_typical", "cap_mim"],
    "ff": ["ff", "res_ff", "mimcap_ff", "cap_mim"],
    "ss": ["ss", "res_ss", "mimcap_ss", "cap_mim"],
}

# --- DUT (same extraction as sim/pvt-postlayout/klt-pex/gen_requests.py) ----
text = SRC.read_text().splitlines()
start = next(i for i, l in enumerate(text) if "expanding" in l and "rcosc_top.sym" in l)
end = next(i for i, l in enumerate(text) if l.strip() == ".end")
block = [l for l in text[start:end] if not l.startswith(("** sym_path:", "** sch_path:"))]
DUT_TEXT = "\n".join(block)
# The DUT is inlined into every bench (one self-contained netlist per request):
# the batch fleet does not reliably stage sibling .include files (klayout-tools#2882).


def set_code(var: str) -> list[str]:
    """control lines that drive VT0..VT7 from the integer vector `var`."""
    out = []
    for i in range(8):
        out.append(f"  let vb = {VDD} * (floor({var} / {1 << i}) - 2 * floor({var} / {1 << (i + 1)}))")
        out.append(f"  alter vt{i} = $&vb")
    return out


def probe(var: str, dest: str) -> list[str]:
    return set_code(var) + [
        "  tran 200p 1200n",
        f"  meas tran ta when v(clk)={VMID:.4f} rise=5",
        f"  meas tran tb when v(clk)={VMID:.4f} rise=25",
        "  let fq = 20 / (tb - ta)",
        "  set fq_s = $&fq",
        "  setplot $sp",
        f"  let {dest} = $fq_s",
    ]


def bench(mismatch: int) -> str:
    L = [
        f"* rcosc_top per-sample trim-selection bench, sw_stat_mismatch={mismatch} (generated by gen_bench.py)",
        f".param sw_stat_global=0 sw_stat_mismatch={mismatch} mc_skew=3 res_mc_skew=3 cap_mc_skew=3 fnoicor=0",
        DUT_TEXT,
        "XXDUT vdd 0 clk t0 t1 t2 t3 t4 t5 t6 t7 rcosc_top",
        f"VDD vdd 0 DC {VDD:g}",
    ] + [f"VT{i} t{i} 0 DC 0" for i in range(8)]
    L += [
        "* Calibration search lives in the body (klt sim owns the final control block; the",
        "* search needs several solves per sample -- see README.md, tool-gap section).",
        ".control",
        "set noaskquit",
        "set measureprec=8",
        "* Each tran makes a new current plot; the search state lives in a plot of its own.",
        "setplot new",
        "set sp = $curplot",
        f"let tgt = {TARGET_HZ:g}",
        "let lo = -1",
        "let hi = 256",
        "let flo = -1e12",
        "let fhi = 1e12",
        "while hi - lo > 1",
        "  let mid = floor((lo + hi) / 2)",
    ]
    L += probe("mid", "fm")
    L += [
        "  if fm < tgt",
        "    let lo = mid",
        "    let flo = fm",
        "  else",
        "    let hi = mid",
        "    let fhi = fm",
        "  end",
        "end",
        "if abs(flo - tgt) <= abs(fhi - tgt)",
        "  let csel = lo",
        "  let fsel = flo",
        "else",
        "  let csel = hi",
        "  let fsel = fhi",
        "end",
        # re-run at the chosen code: proves the held code reproduces the search value
    ]
    L += probe("csel", "fhold")
    L += [
        "let fres_pct = (fhold - tgt) / tgt * 100",
        "let fgap = abs(fhold - fsel)",
        "set v_code = $&csel",
        "set v_fsel = $&fsel",
        "set v_fhold = $&fhold",
        "set v_res = $&fres_pct",
        "set v_gap = $&fgap",
        ".endc",
    ]
    return "\n".join(L) + "\n"


def request(netlist: str, procs: list[str], temps: list[float], mc: dict | None) -> dict:
    req = {
        "netlist": netlist,
        "engine": "ngspice",
        "netlist_source": "schematic",
        "models": {"pdk": "gf180mcuC", "lib": "libs.tech/ngspice/sm141064.ngspice"},
        "corners": {
            "process": [{"name": n, "sections": PROC[n]} for n in procs],
            "temperature_c": temps,
        },
        "analysis": {"kind": "op", "args": ""},
        "measurements": [
            {"name": "code_sel", "expr": "$v_code", "unit": ""},
            {"name": "f_sel_hz", "expr": "$v_fsel", "unit": "Hz"},
            {"name": "f_hold_hz", "expr": "$v_fhold", "unit": "Hz"},
            {"name": "resid_pct", "expr": "$v_res", "unit": "%"},
            {"name": "hold_gap_hz", "expr": "$v_gap", "unit": "Hz"},
        ],
        "batch": {"capacity_wait_s": 1200},
        "options": {"timeout_s": 1800, "keep_artifacts": True},
    }
    if mc:
        req["monte_carlo"] = mc
    return req


def fixed_code_bench() -> str:
    """Fixed-code reference: bits decoded from one DC source `vc` (the code),
    so a `klt sim` supply_v axis sweeps the code.  Independent measurement
    path (file-scope .meas cards, no body .control)."""
    L = [
        "* rcosc_top fixed-code reference, mismatch off (generated by gen_bench.py)",
        ".param sw_stat_global=0 sw_stat_mismatch=0 mc_skew=3 res_mc_skew=3 cap_mc_skew=3 fnoicor=0",
        DUT_TEXT,
        "XXDUT vdd 0 clk t0 t1 t2 t3 t4 t5 t6 t7 rcosc_top",
        f"VDD vdd 0 DC {VDD:g}",
        "VC vc 0 DC 0",
    ]
    for i in range(8):
        L.append(f"BT{i} t{i} 0 V={{{VDD} * (floor(v(vc) / {1 << i}) - 2 * floor(v(vc) / {1 << (i + 1)}))}}")
    return "\n".join(L) + "\n"


def ref_request(codes: list[int]) -> dict:
    r = request("tb_fixedcode.spice", ["tt"], [27], None)
    r["corners"]["supply_v"] = {"vc": [float(c) for c in codes]}
    r["analysis"] = {"kind": "tran", "args": "200p 1200n"}
    r["measurements"] = [
        {"name": "ta", "spice": f".meas tran ta WHEN v(clk)={VMID:.4f} RISE=5", "unit": "s"},
        {"name": "tb", "spice": f".meas tran tb WHEN v(clk)={VMID:.4f} RISE=25", "unit": "s"},
        {"name": "fosc", "spice": ".meas tran fosc PARAM='20/(tb-ta)'", "unit": "Hz"},
    ]
    r["options"]["ngspice_init"] = ["set measureprec=8"]
    return r


if __name__ == "__main__":
    (here / "tb_trimsel_nomm.spice").write_text(bench(0))
    (here / "tb_trimsel_mm.spice").write_text(bench(1))
    (here / "tb_fixedcode.spice").write_text(fixed_code_bench())
    (here / "request_ref_codes.json").write_text(
        json.dumps(ref_request([160, 161, 162, 163, 164, 165]), indent=2) + "\n")
    SEED = 20261008
    reqs = {
        # zero-mismatch control: mismatch off, 3 MC draws -> must be identical and equal the corner
        "request_control_nomm.json": request(
            "tb_trimsel_nomm.spice", ["tt"], [27], {"n": 3, "seed": SEED, "vary": "mismatch"}),
        # smoke: mismatch on, 5 samples (NOT a yield run)
        "request_smoke_mm.json": request(
            "tb_trimsel_mm.spice", ["tt"], [27], {"n": 5, "seed": SEED, "vary": "mismatch"}),
    }
    for name, r in reqs.items():
        (here / name).write_text(json.dumps(r, indent=2) + "\n")
