#!/usr/bin/env bash
# run_checks.sh -- rebuild layout/cells/*.gds and regenerate the committed
# DRC/extract/LVS evidence under layout/reports/ (issues #13, #27).
#
#   layout/run_checks.sh
#
# Covers all five cells of the hierarchy: the two leaf blocks (rcosc_bias,
# rcosc_trim_bank), the two comparators (rcosc_comparator, and since issue #57
# the complementary rcosc_comparator_p) and the full composition (rcosc_top,
# which instantiates the other four as sub-cells).
#
# PDK_ROOT is resolved automatically via `klt pdk find --pdk gf180mcuC` if
# not already set (same convention as design/regen-netlist.sh).
set -euo pipefail

LAYOUT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$LAYOUT_DIR/.." && pwd)"
CELLS_DIR="$LAYOUT_DIR/cells"
LVS_REF_DIR="$LAYOUT_DIR/lvs_ref"
REPORTS_DIR="$LAYOUT_DIR/reports"

mkdir -p "$REPORTS_DIR"

# `build_cells.py` needs the `klayout` python module and `klayout_tools`
# importable (`klt`'s own runtime dependencies). Prefer a plain `python3` that
# already has them; otherwise fall back to the same `uv run` invocation
# build_cells.py's own docstring documents, so a host with `klt` installed as a
# tool (its dependencies isolated in the tool's venv, invisible to `python3`)
# still runs this script unattended.
if python3 -c "import klayout.db, klayout_tools.gen" >/dev/null 2>&1; then
  PYTHON=(python3)
else
  echo "== python3 has no klayout/klayout_tools -- falling back to uv run =="
  PYTHON=(uv run --with klayout --with klayout-tools python3)
fi

# Toolchain pin (added issue #57): every committed GDS and report under
# layout/ was generated by klayout-tools 0.4.0 / klayout 0.30.12 (see the
# provenance block each reports/*.json carries). klt's generator geometry
# is NOT stable across minor versions -- under 0.5.0 the unmodified
# builders draw measurably smaller devices and silently rewrite every
# committed cell -- so refuse to regenerate evidence with a mismatched
# `klt` rather than let a PATH skew invalidate the layout for a reason
# nothing in the diff explains.
KLT_VERSION_EXPECTED="0.4.0"
KLT_VERSION_ACTUAL="$(klt --version 2>/dev/null | head -1 | awk '{print $2}')"
if [ "$KLT_VERSION_ACTUAL" != "$KLT_VERSION_EXPECTED" ]; then
  echo "ERROR: klt ${KLT_VERSION_ACTUAL:-unresolved} != pinned ${KLT_VERSION_EXPECTED}" >&2
  echo "       (layout/reports provenance records klayout-tools ${KLT_VERSION_EXPECTED})." >&2
  echo "       Build the pinned environment first, then re-run with it on PATH:" >&2
  echo "         uv venv /tmp/venv-klt40" >&2
  echo "         uv pip install --python /tmp/venv-klt40/bin/python \"klayout-tools==${KLT_VERSION_EXPECTED}\" klayout==0.30.12" >&2
  echo "         PATH=\"/tmp/venv-klt40/bin:$PATH\" layout/run_checks.sh" >&2
  exit 1
fi

echo "== regenerating design/netlist (source of truth for device geometry) =="
"$REPO_ROOT/design/regen-netlist.sh"

echo "== building layout/cells/*.gds from klt gen primitives =="
"${PYTHON[@]}" "$LAYOUT_DIR/build_cells.py"

CELLS=(rcosc_bias rcosc_trim_bank rcosc_comparator rcosc_comparator_p rcosc_top)

declare -A PINS=(
  [rcosc_bias]="vdd,vh,vl,vss,ibias,pb"
  [rcosc_trim_bank]="p,m,vdd,vss,t0,t1,t2,t3,t4,t5,t6,t7"
  [rcosc_comparator]="vdd,vss,ibias,inp,inn,out"
  [rcosc_comparator_p]="vdd,vss,pb,inp,inn,out"
  [rcosc_top]="vdd,vss,clk,t0,t1,t2,t3,t4,t5,t6,t7"
)

# Extraction deck flavour selections. `poly_res=1k` is this design's
# `ppolyf_u_1k` timing/trim/threshold resistor (DR-0003 sec 5.1/6.1);
# `mim_cap=cap_mim_1f0_m4m5_noshield` is the 1.0 fF/um^2 MiM density the
# schematic's `cap_mim_1f0fF` commits to. Both are one drawn geometry with
# several PDK-offered interpretations, so neither can be inferred from the
# layout -- the design has to say which one it means.
declare -A DECK_OPTIONS=(
  [rcosc_bias]="--deck-option poly_res=1k"
  [rcosc_trim_bank]="--deck-option poly_res=1k"
  [rcosc_comparator]="--deck-option poly_res=1k"
  [rcosc_comparator_p]="--deck-option poly_res=1k"
  [rcosc_top]="--deck-option poly_res=1k --deck-option mim_cap=cap_mim_1f0_m4m5_noshield"
)

# Per-cell `klt lvs` options, each disclosed in the report it produces:
#
#   parameter_tolerance  absorbs the sub-0.1% grid-rounding deltas the 1nm
#                        database unit introduces on the trim bank's short
#                        segments (every tolerated delta is listed with both
#                        original values in the JSON -- see layout/README.md)
#   combine_devices      folds an 8-finger nfet -- the comparator's MTAIL
#                        and (since issue #44's re-spin) the bias core's N2,
#                        both extracting (correctly) as 8 parallel W=2u
#                        nfets -- back into the reference's single W=16u
#                        device. Scoped per-model rather than blanket-true
#                        so it can never quietly merge a series resistor
#                        pair in the bias divider or trim bank.
#                        Load-bearing, not decorative: without it the
#                        comparator LVS reports 7 unmatched devices (and the
#                        re-spun bias cell its own unmatched set). The
#                        complementary comparator (issue #57) needs the same
#                        fold for its three 4-finger *pfets* (MPTAIL and the
#                        MPINN/MPINP pair), so its entry lists "pfet" and
#                        the top's lists both.
#   flatten_reference    the reference is written hierarchically (it reads like
#                        the schematic); `klt extract` always emits the layout
#                        side flat, so the reference is flattened to meet it.
declare -A LVS_OPTIONS=(
  [rcosc_bias]='{"combine_devices": ["nfet"]}'
  [rcosc_trim_bank]='{"parameter_tolerance": 0.001}'
  [rcosc_comparator]='{"combine_devices": ["nfet"]}'
  [rcosc_comparator_p]='{"combine_devices": ["pfet"]}'
  [rcosc_top]='{"combine_devices": ["nfet", "pfet"], "flatten_reference": true, "parameter_tolerance": 0.001}'
)

for cell in "${CELLS[@]}"; do
  gds="$CELLS_DIR/$cell.gds"
  ref="$LVS_REF_DIR/$cell.spice"
  extracted="$REPORTS_DIR/$cell.extracted.spice"

  echo "== $cell: DRC =="
  klt drc "$gds" --deck gf180mcu --top "$cell" --format json > "$REPORTS_DIR/$cell.drc.json"
  python3 -c "
import json, sys
d = json.load(open('$REPORTS_DIR/$cell.drc.json'))
assert d['status'] == 'clean', f\"$cell DRC not clean: {d['violation_count']} violation(s)\"
print('$cell DRC: clean')
"

  echo "== $cell: extract =="
  # shellcheck disable=SC2086  # DECK_OPTIONS is a deliberate word-split flag list
  klt extract "$gds" --deck gf180mcu --top "$cell" ${DECK_OPTIONS[$cell]} \
    --pins "${PINS[$cell]}" --format json -o "$extracted" \
    > "$REPORTS_DIR/$cell.extract.json"

  echo "== $cell: LVS =="
  request=$(OPTIONS_JSON="${LVS_OPTIONS[$cell]}" python3 -c "
import json, os
print(json.dumps({
    'layout': {'netlist': '$extracted', 'top': '$cell'},
    'reference': {'netlist': '$ref', 'top': '$cell', 'form': 'subckt-call', 'deck': 'gf180mcu'},
    'options': json.loads(os.environ['OPTIONS_JSON']),
}))
")
  klt lvs "$request" --format json > "$REPORTS_DIR/$cell.lvs.json"
  python3 -c "
import json
d = json.load(open('$REPORTS_DIR/$cell.lvs.json'))
assert d['status'] == 'match', f\"$cell LVS not a match: {d.get('category_counts')}\"
print('$cell LVS: match', d.get('category_counts') or '(no tolerated deltas)')
"
done

# T1 item 11 (structural power delivery, issue #37; tie declared under
# issue #42): supply-island ERC on the merged top GDS. Unlike the
# DRC/extract/LVS loop above this is one block-level check, not per-cell --
# the question is whether the two supplies each resolve to exactly one
# electrical island on the layers they route on. The spec
# (layout/erc-supply-spec.json) declares Contact deliberately absent (its
# _comment block carries the per-entry justification and both disclosures)
# and one nwell tap tie present -- the upstream deck's own gf180mcu tap
# boolean, added with the #2169-fixed pinned grader under issue #42, so
# erc.missing_tie is computed rather than omitted. The committed report's
# overall "status" is expected to read "violations" -- every real gate
# reports as erc.floating_gate without Contact declared -- which item 11
# explicitly does not grade; the assertion below checks only the item's
# own pass conditions (zero findings naming a declared supply or the
# declared tie, plus a content hash pinning the report to the GDS it was
# run against).
echo "== rcosc_top: ERC (T1 item 11 supply spec) =="
# klt erc (>= 0.5.0, klayout-tools#2115's exit-code rollup) exits 3 whenever
# the report carries ANY finding -- which this report always does, because
# the disclosed erc.floating_gate artifacts (Contact omitted from vias[], see
# the spec's _comment) count as findings. Exit 0 (clean) would be equally
# acceptable; anything else is a real failure and fails the run.
#
# This step runs with repo-relative paths from $REPO_ROOT (the documented
# regeneration command in the spec's _comment) rather than $CELLS_DIR /
# $REPORTS_DIR absolutes: the envelope echoes the paths it is given, and
# `klt signoff` reads the spec the envelope names relative to its own cwd
# (the repo root, in CI's verify-report.py run). An envelope generated with
# absolute paths would record a host-absolute spec path that cannot resolve
# in CI, downgrading item 11's grade to supply_spec_incomplete there.
set +e
( cd "$REPO_ROOT" && klt erc layout/cells/rcosc_top.gds \
    layout/erc-supply-spec.json --format json ) > "$REPORTS_DIR/rcosc_top.erc.json"
erc_rc=$?
set -e
if [ "$erc_rc" -ne 0 ] && [ "$erc_rc" -ne 3 ]; then
  echo "ERROR: klt erc exited $erc_rc (expected 0 or 3)" >&2
  exit 1
fi
python3 -c "
import hashlib, json
d = json.load(open('$REPORTS_DIR/rcosc_top.erc.json'))
supply_rules = ('erc.unconnected_net', 'erc.supply_short',
                'erc.multiply_driven_net', 'erc.missing_tie')
bad = [f for f in d['erc_findings'] if f['rule'] in supply_rules]
assert not bad, 'rcosc_top ERC supply findings: ' + json.dumps(bad)
# klt erc 0.4.0 emits no provenance block (the committed report at every
# prior merge lacks it too), so the content-hash pin can only be checked
# when present -- noted loudly rather than skipped silently.
prov = d.get('provenance')
if prov is None:
    print('note: klt erc 0.4.0 writes no provenance block -- ERC report '
          'content-hash pin unavailable (pre-existing; see issue #57 PR)')
else:
    h = hashlib.sha256(open('$CELLS_DIR/rcosc_top.gds', 'rb').read()).hexdigest()
    assert prov['input']['content_hash'] == 'sha256:' + h, \
        'rcosc_top ERC report does not pin the GDS it was run against'
floating = sum(1 for f in d['erc_findings'] if f['rule'] == 'erc.floating_gate')
print('rcosc_top ERC: vdd and vss each resolve to exactly one island '
      '(zero unconnected_net/supply_short), and every merged n-well '
      'carries a declared vdd-reached tap (zero missing_tie); '
      f'{floating} floating-gate finding(s) = the disclosed Contact-omission '
      'artifact (klayout-tools#2183), graded as absent by item 11')
"

echo "== all checks passed =="
