v {xschem version=3.4.7 file_version=1.2
* rcosc_bias -- ratiometric threshold + current-bias generator (issue #6)
*
* Three equal ppolyf_u_1k resistors (gf180mcu Sec 6.1A, 1000 ohm/sq typ,
* same flavor DR-0003 sources its TCR figure from: -1200 ppm/K worst
* magnitude) divide VDD into vh = 2/3 VDD and vl = 1/3 VDD -- the two
* threshold comparators in rcosc_top.sch compare the RC timing node
* against these. Because vh/vl scale directly with VDD, the switching
* thresholds are ratiometric to the supply (first-order supply tracking,
* DR-0001's "simpler ratiometric scheme" option) rather than an absolute
* bandgap-style reference.
*
* Current-reference re-architected issue #39: the pre-#39 reference was
* RBIAS from VDD into a diode-connected nfet, ibias ~= (VDD - VGS)/R --
* measured +24.5% supply sensitivity over 3.0->3.6 V (sim/pvt grid, issue
* #39 instrumentation) and ~+900 ppm/K temperature drift. The comparator
* path's delay/overdrive error is paid roughly 3x into the charge phase
* (slope-to-threshold conversion at vh, see the issue #16 writeup in
* design/README.md), so that current-reference sensitivity appeared in
* the free-running frequency as the +20.77% (ss) / +8.52% (tt)
* post-trim supply rows of the 20260907T090653Z campaign -- the dominant
* unbudgeted post-trim residual DR-0006 isolated (comparator/bias-path
* PVT sensitivity, never budgeted by DR-0003's timing-TCR-only
* derivation).
*
* The new core is a self-biased (supply-independent) beta-multiplier:
*   P1 (diode, source vdd, gate/drain pb) + P2 mirror feed two matched
*   branches; N1 (W=2u L=1u, diode-connected) is the reference unit --
*   its gate node IS the exported ibias net, so rcosc_comparator.sch's
*   MTAIL (W=16u nf=8) continues to mirror it 8:1 exactly as it mirrored
*   the old MBIASD, unchanged; N2 (W=16u nf=8, gate ibias, source
*   degenerated by RZ) closes the loop through the P mirror: the loop
*   equates the N1/N2 VGS difference across RZ, and VDD appears nowhere
*   in that constraint. SEED (nfet_03v3 W=2u L=20u, gate at vl, drain
*   at the PMOS gate bus pb, source vss) is a weak always-on pull-down
*   (~1 uA) that guarantees the loop's zero-current state is not a
*   stable operating point: in the dead state pb rests at vdd, the
*   pull-down regenerates the diode/mirror loop, and once alive the
*   injector's sub-uA draw is absorbed into the reference calibration.
*   Its gate draws no DC from the vl divider (gate only), keeping the
*   ratiometric thresholds unperturbed.
*
* The threshold divider (RBA/RBB/RBC) and the vh/vl ratiometric behavior
* are UNCHANGED by issue #39; only the RBIAS/MBIASD current-reference
* leg is replaced. This is NOT an attempt to compensate the timing
* resistor's -1200 ppm/K TCR (DR-0004 stands); it restores the "fixed
* voltage/current reference" assumption DR-0003's post-trim accuracy
* derivation was built on, per DR-0006's sanctioned follow-up.
}
G {}
K {}
V {}
S {}
E {}
C {symbols/ppolyf_u_1k.sym} 0 0 0 0 {name=RBA model=ppolyf_u_1k W=2u L=100u m=1}
N 0 30 0 50 {}
C {lab_pin.sym} 0 50 0 0 {name=l1 lab=vdd}
N 0 -30 0 -50 {}
C {lab_pin.sym} 0 -50 0 0 {name=l2 lab=vh}
N -20 0 -40 0 {}
C {lab_pin.sym} -40 0 0 0 {name=l3 lab=vss}
C {symbols/ppolyf_u_1k.sym} 200 0 0 0 {name=RBB model=ppolyf_u_1k W=2u L=100u m=1}
N 200 30 200 50 {}
C {lab_pin.sym} 200 50 0 0 {name=l4 lab=vh}
N 200 -30 200 -50 {}
C {lab_pin.sym} 200 -50 0 0 {name=l5 lab=vl}
N 180 0 160 0 {}
C {lab_pin.sym} 160 0 0 0 {name=l6 lab=vss}
C {symbols/ppolyf_u_1k.sym} 400 0 0 0 {name=RBC model=ppolyf_u_1k W=2u L=100u m=1}
N 400 30 400 50 {}
C {lab_pin.sym} 400 50 0 0 {name=l7 lab=vl}
N 400 -30 400 -50 {}
C {lab_pin.sym} 400 -50 0 0 {name=l8 lab=vss}
N 380 0 360 0 {}
C {lab_pin.sym} 360 0 0 0 {name=l9 lab=vss}
C {symbols/nfet_03v3.sym} 600 0 0 0 {name=N1 model=nfet_03v3 W=2u L=1u nf=1 m=1}
N 620 -30 620 -50 {}
C {lab_pin.sym} 620 -50 0 0 {name=l10 lab=ibias}
N 580 0 560 0 {}
C {lab_pin.sym} 560 0 0 0 {name=l11 lab=ibias}
N 620 30 620 50 {}
C {lab_pin.sym} 620 50 0 0 {name=l12 lab=vss}
N 620 0 640 0 {}
C {lab_pin.sym} 640 0 0 0 {name=l13 lab=vss}
C {symbols/nfet_03v3.sym} 800 0 0 0 {name=N2 model=nfet_03v3 W=16u L=1u nf=8 m=1}
N 820 -30 820 -50 {}
C {lab_pin.sym} 820 -50 0 0 {name=l14 lab=pb}
N 780 0 760 0 {}
C {lab_pin.sym} 760 0 0 0 {name=l15 lab=ibias}
N 820 30 820 50 {}
C {lab_pin.sym} 820 50 0 0 {name=l16 lab=n2s}
N 820 0 840 0 {}
C {lab_pin.sym} 840 0 0 0 {name=l17 lab=vss}
C {symbols/ppolyf_u_1k.sym} 800 200 0 0 {name=RZ model=ppolyf_u_1k W=2u L=32u m=1}
N 800 230 800 250 {}
C {lab_pin.sym} 800 250 0 0 {name=l18 lab=n2s}
N 800 170 800 150 {}
C {lab_pin.sym} 800 150 0 0 {name=l19 lab=vss}
N 780 200 760 200 {}
C {lab_pin.sym} 760 200 0 0 {name=l19b lab=vss}
C {symbols/pfet_03v3.sym} 1000 0 0 0 {name=P1 model=pfet_03v3 W=4u L=1u nf=1 m=1}
N 1020 -30 1020 -50 {}
C {lab_pin.sym} 1020 -50 0 0 {name=l20 lab=vdd}
N 980 0 960 0 {}
C {lab_pin.sym} 960 0 0 0 {name=l21 lab=pb}
N 1020 30 1020 50 {}
C {lab_pin.sym} 1020 50 0 0 {name=l22 lab=pb}
N 1020 0 1040 0 {}
C {lab_pin.sym} 1040 0 0 0 {name=l23 lab=vdd}
C {symbols/pfet_03v3.sym} 1200 0 0 0 {name=P2 model=pfet_03v3 W=4u L=1u nf=1 m=1}
N 1220 -30 1220 -50 {}
C {lab_pin.sym} 1220 -50 0 0 {name=l24 lab=vdd}
N 1180 0 1160 0 {}
C {lab_pin.sym} 1160 0 0 0 {name=l25 lab=pb}
N 1220 30 1220 50 {}
C {lab_pin.sym} 1220 50 0 0 {name=l26 lab=ibias}
N 1220 0 1240 0 {}
C {lab_pin.sym} 1240 0 0 0 {name=l27 lab=vdd}
C {symbols/nfet_03v3.sym} 1400 0 0 0 {name=SEED model=nfet_03v3 W=2u L=20u nf=1 m=1}
N 1420 -30 1420 -50 {}
C {lab_pin.sym} 1420 -50 0 0 {name=l28 lab=pb}
N 1380 0 1360 0 {}
C {lab_pin.sym} 1360 0 0 0 {name=l29 lab=vl}
N 1420 30 1420 50 {}
C {lab_pin.sym} 1420 50 0 0 {name=l30 lab=vss}
N 1420 0 1440 0 {}
C {lab_pin.sym} 1440 0 0 0 {name=l31 lab=vss}
C {iopin.sym} -200 300 0 0 {name=p32 lab=vdd}
C {iopin.sym} -200 240 0 0 {name=p33 lab=vss}
C {iopin.sym} -200 180 0 0 {name=p34 lab=vh}
C {iopin.sym} -200 120 0 0 {name=p35 lab=vl}
C {iopin.sym} -200 60 0 0 {name=p36 lab=ibias}
