v {xschem version=3.4.7 file_version=1.2
* rcosc_trim_bank -- 8-bit binary-weighted switched-resistor trim bank
* (issue #6, re-sized issue #16, switch restructure issue #43). Targets
* DR-0003's ratified +/-40%% (28.8-67.2 MHz) trim range in 256 monotonic
* codes. p = top (charge-path side), m = bottom (RC integrator node side),
* t0..t7 = trim bits (t7 = MSB, weight 128), vdd = logic/inverter supply.
*
* Sizing (issue #16): R values re-derived from SIMULATED transient charge-
* time behavior at the reference corner against the resized (higher-
* current) rcosc_bias.sch -- see design/README.md "Trim bank sizing" for
* the full root-cause writeup and derivation. RFIX/R0..R7 values are
* NOT touched by issue #43 (one issue, one mechanism).
*
* Pass-switch restructure (issue #43): pre-#43 the shunt for segment R_i
* was a single nfet pass switch (gate = t_i, bulk = vss), effective drive
* t_i - v(low node). As the timing node rises toward vh = 2/3*VDD the
* chain node behind the switch rises with it, body effect pushes VTH up,
* and mid/upper switches collapse into subthreshold: dead mid-block trim
* steps and a PVT-dependent "phantom" series resistance (issue #43
* instrumentation; DR-0012). The shunt for each segment is now a
* transmission gate: nfet SW<i> (gate = t_i, bulk = vss) in parallel
* with pfet PW<i> (gate = tb_i, the locally inverted bit, bulk = vdd).
* The nfet serves the low-node end of the shunt range, the pfet the
* high-node end (its |VGS| grows with node voltage), tiling the full
* 0..VDD node swing with no drive-dead region. tb_i is generated by a
* per-bit CMOS inverter (NINV<i>/PINV<i>, 2u/4u, L=0.5u) on the cell's
* own vdd/vss rails; static current is zero (trim bits are quasi-DC),
* so DR-0003 Row 4 is unaffected by the inverters themselves.
*
* Switch sizing (issue #43, gridded from transient data, not closed
* form): pass devices run at L=0.28u (the DRM PL.2 gate-poly2 minimum
* for the 3.3V column; the sm141064 nfet_03v3/pfet_03v3 subckt default
* l) -- at m-adjacent positions the on-channel gate capacitance loads
* the ~270 fF timing node directly, and 0.28u buys ~1.8x the Ron per
* width at ~0.56x the channel cap of 0.5u. Widths are per-position,
* tapered down the ladder toward m where the cap couples hard and up
* the ladder where the segment resist falls to the LSB scale:
*   bit:      0    1    2    3   4   5   6   7   (W = SW<i> = PW<i>)
*   W (um):  24   16   12    8   6   5   4   3
* Known, characterized limit of this restructure (documented in
* DR-0013, do not paper over): with the issue-#16-frozen R map, every
* block-boundary code pair (0xkF -> 0x(k+1)0) has only ~1 LSB-R
* (~374 ohm, R_maxbit minus the sum below it) of ideal-switch
* monotonicity margin. A realizable shunt's trip-weighted residual
* exceeds that at slow corners (all of it lands on the timing node at
* bit 7), so a few boundary pairs dip a few percent locally at PVT
* extremes (measured: -6.4% worst, 0x7F->0x80 at tt). The block-
* staircase stays monotone at every sampled code; the campaign's
* calibration documents the dips and picks codes accordingly.
}
G {}
K {}
V {}
S {}
E {}
C {symbols/ppolyf_u_1k.sym} 0 0 0 0 {name=RFIX model=ppolyf_u_1k W=2u L=17.198u m=1}
N 0 30 0 50 {}
C {lab_pin.sym} 0 50 0 0 {name=l1 lab=p}
N 0 -30 0 -50 {}
C {lab_pin.sym} 0 -50 0 0 {name=l2 lab=c1}
N -20 0 -40 0 {}
C {lab_pin.sym} -40 0 0 0 {name=l3 lab=vss}
C {symbols/ppolyf_u_1k.sym} 200 0 0 0 {name=R0 model=ppolyf_u_1k W=2u L=0.7482u m=1}
N 200 30 200 50 {}
C {lab_pin.sym} 200 50 0 0 {name=l7 lab=c1}
N 200 -30 200 -50 {}
C {lab_pin.sym} 200 -50 0 0 {name=l8 lab=c2}
N 180 0 160 0 {}
C {lab_pin.sym} 160 0 0 0 {name=l9 lab=vss}
C {symbols/nfet_03v3.sym} 200 -300 0 0 {name=SW0 model=nfet_03v3 W=24uu L=0.28u nf=1 m=1}
N 220 -330 220 -350 {}
C {lab_pin.sym} 220 -350 0 0 {name=ln0a lab=c1}
N 180 -300 160 -300 {}
C {lab_pin.sym} 160 -300 0 0 {name=ln0b lab=t0}
N 220 -270 220 -250 {}
C {lab_pin.sym} 220 -250 0 0 {name=ln0c lab=c2}
N 220 -300 240 -300 {}
C {lab_pin.sym} 240 -300 0 0 {name=ln0d lab=vss}
C {symbols/pfet_03v3.sym} 200 -440 0 0 {name=PW0 model=pfet_03v3 W=24uu L=0.28u nf=1 m=1}
N 220 -470 220 -490 {}
C {lab_pin.sym} 220 -490 0 0 {name=lp0a lab=c1}
N 220 -410 220 -390 {}
C {lab_pin.sym} 220 -390 0 0 {name=lp0b lab=c2}
N 180 -440 160 -440 {}
C {lab_pin.sym} 160 -440 0 0 {name=lp0c lab=tb0}
N 220 -440 240 -440 {}
C {lab_pin.sym} 240 -440 0 0 {name=lp0d lab=vdd}
C {symbols/nfet_03v3.sym} 200 -620 0 0 {name=NINV0 model=nfet_03v3 W=2u L=0.5u nf=1 m=1}
N 220 -650 220 -670 {}
C {lab_pin.sym} 220 -670 0 0 {name=lv0a lab=tb0}
N 180 -620 160 -620 {}
C {lab_pin.sym} 160 -620 0 0 {name=lv0b lab=t0}
N 220 -590 220 -570 {}
C {lab_pin.sym} 220 -570 0 0 {name=lv0c lab=vss}
N 220 -620 240 -620 {}
C {lab_pin.sym} 240 -620 0 0 {name=lv0d lab=vss}
C {symbols/pfet_03v3.sym} 260 -760 0 0 {name=PINV0 model=pfet_03v3 W=4u L=0.5u nf=1 m=1}
N 280 -790 280 -810 {}
C {lab_pin.sym} 280 -810 0 0 {name=lw0a lab=vdd}
N 280 -730 280 -710 {}
C {lab_pin.sym} 280 -710 0 0 {name=lw0b lab=tb0}
N 240 -760 220 -760 {}
C {lab_pin.sym} 220 -760 0 0 {name=lw0c lab=t0}
N 280 -760 300 -760 {}
C {lab_pin.sym} 300 -760 0 0 {name=lw0d lab=vdd}
C {symbols/ppolyf_u_1k.sym} 400 0 0 0 {name=R1 model=ppolyf_u_1k W=2u L=1.4965u m=1}
N 400 30 400 50 {}
C {lab_pin.sym} 400 50 0 0 {name=l10 lab=c2}
N 400 -30 400 -50 {}
C {lab_pin.sym} 400 -50 0 0 {name=l11 lab=c3}
N 380 0 360 0 {}
C {lab_pin.sym} 360 0 0 0 {name=l12 lab=vss}
C {symbols/nfet_03v3.sym} 400 -300 0 0 {name=SW1 model=nfet_03v3 W=16uu L=0.28u nf=1 m=1}
N 420 -330 420 -350 {}
C {lab_pin.sym} 420 -350 0 0 {name=ln1a lab=c2}
N 380 -300 360 -300 {}
C {lab_pin.sym} 360 -300 0 0 {name=ln1b lab=t1}
N 420 -270 420 -250 {}
C {lab_pin.sym} 420 -250 0 0 {name=ln1c lab=c3}
N 420 -300 440 -300 {}
C {lab_pin.sym} 440 -300 0 0 {name=ln1d lab=vss}
C {symbols/pfet_03v3.sym} 400 -440 0 0 {name=PW1 model=pfet_03v3 W=16uu L=0.28u nf=1 m=1}
N 420 -470 420 -490 {}
C {lab_pin.sym} 420 -490 0 0 {name=lp1a lab=c2}
N 420 -410 420 -390 {}
C {lab_pin.sym} 420 -390 0 0 {name=lp1b lab=c3}
N 380 -440 360 -440 {}
C {lab_pin.sym} 360 -440 0 0 {name=lp1c lab=tb1}
N 420 -440 440 -440 {}
C {lab_pin.sym} 440 -440 0 0 {name=lp1d lab=vdd}
C {symbols/nfet_03v3.sym} 400 -620 0 0 {name=NINV1 model=nfet_03v3 W=2u L=0.5u nf=1 m=1}
N 420 -650 420 -670 {}
C {lab_pin.sym} 420 -670 0 0 {name=lv1a lab=tb1}
N 380 -620 360 -620 {}
C {lab_pin.sym} 360 -620 0 0 {name=lv1b lab=t1}
N 420 -590 420 -570 {}
C {lab_pin.sym} 420 -570 0 0 {name=lv1c lab=vss}
N 420 -620 440 -620 {}
C {lab_pin.sym} 440 -620 0 0 {name=lv1d lab=vss}
C {symbols/pfet_03v3.sym} 460 -760 0 0 {name=PINV1 model=pfet_03v3 W=4u L=0.5u nf=1 m=1}
N 480 -790 480 -810 {}
C {lab_pin.sym} 480 -810 0 0 {name=lw1a lab=vdd}
N 480 -730 480 -710 {}
C {lab_pin.sym} 480 -710 0 0 {name=lw1b lab=tb1}
N 440 -760 420 -760 {}
C {lab_pin.sym} 420 -760 0 0 {name=lw1c lab=t1}
N 480 -760 500 -760 {}
C {lab_pin.sym} 500 -760 0 0 {name=lw1d lab=vdd}
C {symbols/ppolyf_u_1k.sym} 600 0 0 0 {name=R2 model=ppolyf_u_1k W=2u L=2.993u m=1}
N 600 30 600 50 {}
C {lab_pin.sym} 600 50 0 0 {name=l13 lab=c3}
N 600 -30 600 -50 {}
C {lab_pin.sym} 600 -50 0 0 {name=l14 lab=c4}
N 580 0 560 0 {}
C {lab_pin.sym} 560 0 0 0 {name=l15 lab=vss}
C {symbols/nfet_03v3.sym} 600 -300 0 0 {name=SW2 model=nfet_03v3 W=12uu L=0.28u nf=1 m=1}
N 620 -330 620 -350 {}
C {lab_pin.sym} 620 -350 0 0 {name=ln2a lab=c3}
N 580 -300 560 -300 {}
C {lab_pin.sym} 560 -300 0 0 {name=ln2b lab=t2}
N 620 -270 620 -250 {}
C {lab_pin.sym} 620 -250 0 0 {name=ln2c lab=c4}
N 620 -300 640 -300 {}
C {lab_pin.sym} 640 -300 0 0 {name=ln2d lab=vss}
C {symbols/pfet_03v3.sym} 600 -440 0 0 {name=PW2 model=pfet_03v3 W=12uu L=0.28u nf=1 m=1}
N 620 -470 620 -490 {}
C {lab_pin.sym} 620 -490 0 0 {name=lp2a lab=c3}
N 620 -410 620 -390 {}
C {lab_pin.sym} 620 -390 0 0 {name=lp2b lab=c4}
N 580 -440 560 -440 {}
C {lab_pin.sym} 560 -440 0 0 {name=lp2c lab=tb2}
N 620 -440 640 -440 {}
C {lab_pin.sym} 640 -440 0 0 {name=lp2d lab=vdd}
C {symbols/nfet_03v3.sym} 600 -620 0 0 {name=NINV2 model=nfet_03v3 W=2u L=0.5u nf=1 m=1}
N 620 -650 620 -670 {}
C {lab_pin.sym} 620 -670 0 0 {name=lv2a lab=tb2}
N 580 -620 560 -620 {}
C {lab_pin.sym} 560 -620 0 0 {name=lv2b lab=t2}
N 620 -590 620 -570 {}
C {lab_pin.sym} 620 -570 0 0 {name=lv2c lab=vss}
N 620 -620 640 -620 {}
C {lab_pin.sym} 640 -620 0 0 {name=lv2d lab=vss}
C {symbols/pfet_03v3.sym} 660 -760 0 0 {name=PINV2 model=pfet_03v3 W=4u L=0.5u nf=1 m=1}
N 680 -790 680 -810 {}
C {lab_pin.sym} 680 -810 0 0 {name=lw2a lab=vdd}
N 680 -730 680 -710 {}
C {lab_pin.sym} 680 -710 0 0 {name=lw2b lab=tb2}
N 640 -760 620 -760 {}
C {lab_pin.sym} 620 -760 0 0 {name=lw2c lab=t2}
N 680 -760 700 -760 {}
C {lab_pin.sym} 700 -760 0 0 {name=lw2d lab=vdd}
C {symbols/ppolyf_u_1k.sym} 800 0 0 0 {name=R3 model=ppolyf_u_1k W=2u L=5.9859u m=1}
N 800 30 800 50 {}
C {lab_pin.sym} 800 50 0 0 {name=l16 lab=c4}
N 800 -30 800 -50 {}
C {lab_pin.sym} 800 -50 0 0 {name=l17 lab=c5}
N 780 0 760 0 {}
C {lab_pin.sym} 760 0 0 0 {name=l18 lab=vss}
C {symbols/nfet_03v3.sym} 800 -300 0 0 {name=SW3 model=nfet_03v3 W=8uu L=0.28u nf=1 m=1}
N 820 -330 820 -350 {}
C {lab_pin.sym} 820 -350 0 0 {name=ln3a lab=c4}
N 780 -300 760 -300 {}
C {lab_pin.sym} 760 -300 0 0 {name=ln3b lab=t3}
N 820 -270 820 -250 {}
C {lab_pin.sym} 820 -250 0 0 {name=ln3c lab=c5}
N 820 -300 840 -300 {}
C {lab_pin.sym} 840 -300 0 0 {name=ln3d lab=vss}
C {symbols/pfet_03v3.sym} 800 -440 0 0 {name=PW3 model=pfet_03v3 W=8uu L=0.28u nf=1 m=1}
N 820 -470 820 -490 {}
C {lab_pin.sym} 820 -490 0 0 {name=lp3a lab=c4}
N 820 -410 820 -390 {}
C {lab_pin.sym} 820 -390 0 0 {name=lp3b lab=c5}
N 780 -440 760 -440 {}
C {lab_pin.sym} 760 -440 0 0 {name=lp3c lab=tb3}
N 820 -440 840 -440 {}
C {lab_pin.sym} 840 -440 0 0 {name=lp3d lab=vdd}
C {symbols/nfet_03v3.sym} 800 -620 0 0 {name=NINV3 model=nfet_03v3 W=2u L=0.5u nf=1 m=1}
N 820 -650 820 -670 {}
C {lab_pin.sym} 820 -670 0 0 {name=lv3a lab=tb3}
N 780 -620 760 -620 {}
C {lab_pin.sym} 760 -620 0 0 {name=lv3b lab=t3}
N 820 -590 820 -570 {}
C {lab_pin.sym} 820 -570 0 0 {name=lv3c lab=vss}
N 820 -620 840 -620 {}
C {lab_pin.sym} 840 -620 0 0 {name=lv3d lab=vss}
C {symbols/pfet_03v3.sym} 860 -760 0 0 {name=PINV3 model=pfet_03v3 W=4u L=0.5u nf=1 m=1}
N 880 -790 880 -810 {}
C {lab_pin.sym} 880 -810 0 0 {name=lw3a lab=vdd}
N 880 -730 880 -710 {}
C {lab_pin.sym} 880 -710 0 0 {name=lw3b lab=tb3}
N 840 -760 820 -760 {}
C {lab_pin.sym} 820 -760 0 0 {name=lw3c lab=t3}
N 880 -760 900 -760 {}
C {lab_pin.sym} 900 -760 0 0 {name=lw3d lab=vdd}
C {symbols/ppolyf_u_1k.sym} 1000 0 0 0 {name=R4 model=ppolyf_u_1k W=2u L=11.9719u m=1}
N 1000 30 1000 50 {}
C {lab_pin.sym} 1000 50 0 0 {name=l19 lab=c5}
N 1000 -30 1000 -50 {}
C {lab_pin.sym} 1000 -50 0 0 {name=l20 lab=c6}
N 980 0 960 0 {}
C {lab_pin.sym} 960 0 0 0 {name=l21 lab=vss}
C {symbols/nfet_03v3.sym} 1000 -300 0 0 {name=SW4 model=nfet_03v3 W=6uu L=0.28u nf=1 m=1}
N 1020 -330 1020 -350 {}
C {lab_pin.sym} 1020 -350 0 0 {name=ln4a lab=c5}
N 980 -300 960 -300 {}
C {lab_pin.sym} 960 -300 0 0 {name=ln4b lab=t4}
N 1020 -270 1020 -250 {}
C {lab_pin.sym} 1020 -250 0 0 {name=ln4c lab=c6}
N 1020 -300 1040 -300 {}
C {lab_pin.sym} 1040 -300 0 0 {name=ln4d lab=vss}
C {symbols/pfet_03v3.sym} 1000 -440 0 0 {name=PW4 model=pfet_03v3 W=6uu L=0.28u nf=1 m=1}
N 1020 -470 1020 -490 {}
C {lab_pin.sym} 1020 -490 0 0 {name=lp4a lab=c5}
N 1020 -410 1020 -390 {}
C {lab_pin.sym} 1020 -390 0 0 {name=lp4b lab=c6}
N 980 -440 960 -440 {}
C {lab_pin.sym} 960 -440 0 0 {name=lp4c lab=tb4}
N 1020 -440 1040 -440 {}
C {lab_pin.sym} 1040 -440 0 0 {name=lp4d lab=vdd}
C {symbols/nfet_03v3.sym} 1000 -620 0 0 {name=NINV4 model=nfet_03v3 W=2u L=0.5u nf=1 m=1}
N 1020 -650 1020 -670 {}
C {lab_pin.sym} 1020 -670 0 0 {name=lv4a lab=tb4}
N 980 -620 960 -620 {}
C {lab_pin.sym} 960 -620 0 0 {name=lv4b lab=t4}
N 1020 -590 1020 -570 {}
C {lab_pin.sym} 1020 -570 0 0 {name=lv4c lab=vss}
N 1020 -620 1040 -620 {}
C {lab_pin.sym} 1040 -620 0 0 {name=lv4d lab=vss}
C {symbols/pfet_03v3.sym} 1060 -760 0 0 {name=PINV4 model=pfet_03v3 W=4u L=0.5u nf=1 m=1}
N 1080 -790 1080 -810 {}
C {lab_pin.sym} 1080 -810 0 0 {name=lw4a lab=vdd}
N 1080 -730 1080 -710 {}
C {lab_pin.sym} 1080 -710 0 0 {name=lw4b lab=tb4}
N 1040 -760 1020 -760 {}
C {lab_pin.sym} 1020 -760 0 0 {name=lw4c lab=t4}
N 1080 -760 1100 -760 {}
C {lab_pin.sym} 1100 -760 0 0 {name=lw4d lab=vdd}
C {symbols/ppolyf_u_1k.sym} 1200 0 0 0 {name=R5 model=ppolyf_u_1k W=2u L=23.9438u m=1}
N 1200 30 1200 50 {}
C {lab_pin.sym} 1200 50 0 0 {name=l22 lab=c6}
N 1200 -30 1200 -50 {}
C {lab_pin.sym} 1200 -50 0 0 {name=l23 lab=c7}
N 1180 0 1160 0 {}
C {lab_pin.sym} 1160 0 0 0 {name=l24 lab=vss}
C {symbols/nfet_03v3.sym} 1200 -300 0 0 {name=SW5 model=nfet_03v3 W=5uu L=0.28u nf=1 m=1}
N 1220 -330 1220 -350 {}
C {lab_pin.sym} 1220 -350 0 0 {name=ln5a lab=c6}
N 1180 -300 1160 -300 {}
C {lab_pin.sym} 1160 -300 0 0 {name=ln5b lab=t5}
N 1220 -270 1220 -250 {}
C {lab_pin.sym} 1220 -250 0 0 {name=ln5c lab=c7}
N 1220 -300 1240 -300 {}
C {lab_pin.sym} 1240 -300 0 0 {name=ln5d lab=vss}
C {symbols/pfet_03v3.sym} 1200 -440 0 0 {name=PW5 model=pfet_03v3 W=5uu L=0.28u nf=1 m=1}
N 1220 -470 1220 -490 {}
C {lab_pin.sym} 1220 -490 0 0 {name=lp5a lab=c6}
N 1220 -410 1220 -390 {}
C {lab_pin.sym} 1220 -390 0 0 {name=lp5b lab=c7}
N 1180 -440 1160 -440 {}
C {lab_pin.sym} 1160 -440 0 0 {name=lp5c lab=tb5}
N 1220 -440 1240 -440 {}
C {lab_pin.sym} 1240 -440 0 0 {name=lp5d lab=vdd}
C {symbols/nfet_03v3.sym} 1200 -620 0 0 {name=NINV5 model=nfet_03v3 W=2u L=0.5u nf=1 m=1}
N 1220 -650 1220 -670 {}
C {lab_pin.sym} 1220 -670 0 0 {name=lv5a lab=tb5}
N 1180 -620 1160 -620 {}
C {lab_pin.sym} 1160 -620 0 0 {name=lv5b lab=t5}
N 1220 -590 1220 -570 {}
C {lab_pin.sym} 1220 -570 0 0 {name=lv5c lab=vss}
N 1220 -620 1240 -620 {}
C {lab_pin.sym} 1240 -620 0 0 {name=lv5d lab=vss}
C {symbols/pfet_03v3.sym} 1260 -760 0 0 {name=PINV5 model=pfet_03v3 W=4u L=0.5u nf=1 m=1}
N 1280 -790 1280 -810 {}
C {lab_pin.sym} 1280 -810 0 0 {name=lw5a lab=vdd}
N 1280 -730 1280 -710 {}
C {lab_pin.sym} 1280 -710 0 0 {name=lw5b lab=tb5}
N 1240 -760 1220 -760 {}
C {lab_pin.sym} 1220 -760 0 0 {name=lw5c lab=t5}
N 1280 -760 1300 -760 {}
C {lab_pin.sym} 1300 -760 0 0 {name=lw5d lab=vdd}
C {symbols/ppolyf_u_1k.sym} 1400 0 0 0 {name=R6 model=ppolyf_u_1k W=2u L=47.8876u m=1}
N 1400 30 1400 50 {}
C {lab_pin.sym} 1400 50 0 0 {name=l25 lab=c7}
N 1400 -30 1400 -50 {}
C {lab_pin.sym} 1400 -50 0 0 {name=l26 lab=c8}
N 1380 0 1360 0 {}
C {lab_pin.sym} 1360 0 0 0 {name=l27 lab=vss}
C {symbols/nfet_03v3.sym} 1400 -300 0 0 {name=SW6 model=nfet_03v3 W=4uu L=0.28u nf=1 m=1}
N 1420 -330 1420 -350 {}
C {lab_pin.sym} 1420 -350 0 0 {name=ln6a lab=c7}
N 1380 -300 1360 -300 {}
C {lab_pin.sym} 1360 -300 0 0 {name=ln6b lab=t6}
N 1420 -270 1420 -250 {}
C {lab_pin.sym} 1420 -250 0 0 {name=ln6c lab=c8}
N 1420 -300 1440 -300 {}
C {lab_pin.sym} 1440 -300 0 0 {name=ln6d lab=vss}
C {symbols/pfet_03v3.sym} 1400 -440 0 0 {name=PW6 model=pfet_03v3 W=4uu L=0.28u nf=1 m=1}
N 1420 -470 1420 -490 {}
C {lab_pin.sym} 1420 -490 0 0 {name=lp6a lab=c7}
N 1420 -410 1420 -390 {}
C {lab_pin.sym} 1420 -390 0 0 {name=lp6b lab=c8}
N 1380 -440 1360 -440 {}
C {lab_pin.sym} 1360 -440 0 0 {name=lp6c lab=tb6}
N 1420 -440 1440 -440 {}
C {lab_pin.sym} 1440 -440 0 0 {name=lp6d lab=vdd}
C {symbols/nfet_03v3.sym} 1400 -620 0 0 {name=NINV6 model=nfet_03v3 W=2u L=0.5u nf=1 m=1}
N 1420 -650 1420 -670 {}
C {lab_pin.sym} 1420 -670 0 0 {name=lv6a lab=tb6}
N 1380 -620 1360 -620 {}
C {lab_pin.sym} 1360 -620 0 0 {name=lv6b lab=t6}
N 1420 -590 1420 -570 {}
C {lab_pin.sym} 1420 -570 0 0 {name=lv6c lab=vss}
N 1420 -620 1440 -620 {}
C {lab_pin.sym} 1440 -620 0 0 {name=lv6d lab=vss}
C {symbols/pfet_03v3.sym} 1460 -760 0 0 {name=PINV6 model=pfet_03v3 W=4u L=0.5u nf=1 m=1}
N 1480 -790 1480 -810 {}
C {lab_pin.sym} 1480 -810 0 0 {name=lw6a lab=vdd}
N 1480 -730 1480 -710 {}
C {lab_pin.sym} 1480 -710 0 0 {name=lw6b lab=tb6}
N 1440 -760 1420 -760 {}
C {lab_pin.sym} 1420 -760 0 0 {name=lw6c lab=t6}
N 1480 -760 1500 -760 {}
C {lab_pin.sym} 1500 -760 0 0 {name=lw6d lab=vdd}
C {symbols/ppolyf_u_1k.sym} 1600 0 0 0 {name=R7 model=ppolyf_u_1k W=2u L=95.7751u m=1}
N 1600 30 1600 50 {}
C {lab_pin.sym} 1600 50 0 0 {name=l28 lab=c8}
N 1600 -30 1600 -50 {}
C {lab_pin.sym} 1600 -50 0 0 {name=l29 lab=m}
N 1580 0 1560 0 {}
C {lab_pin.sym} 1560 0 0 0 {name=l30 lab=vss}
C {symbols/nfet_03v3.sym} 1600 -300 0 0 {name=SW7 model=nfet_03v3 W=3uu L=0.28u nf=1 m=1}
N 1620 -330 1620 -350 {}
C {lab_pin.sym} 1620 -350 0 0 {name=ln7a lab=c8}
N 1580 -300 1560 -300 {}
C {lab_pin.sym} 1560 -300 0 0 {name=ln7b lab=t7}
N 1620 -270 1620 -250 {}
C {lab_pin.sym} 1620 -250 0 0 {name=ln7c lab=m}
N 1620 -300 1640 -300 {}
C {lab_pin.sym} 1640 -300 0 0 {name=ln7d lab=vss}
C {symbols/pfet_03v3.sym} 1600 -440 0 0 {name=PW7 model=pfet_03v3 W=3uu L=0.28u nf=1 m=1}
N 1620 -470 1620 -490 {}
C {lab_pin.sym} 1620 -490 0 0 {name=lp7a lab=c8}
N 1620 -410 1620 -390 {}
C {lab_pin.sym} 1620 -390 0 0 {name=lp7b lab=m}
N 1580 -440 1560 -440 {}
C {lab_pin.sym} 1560 -440 0 0 {name=lp7c lab=tb7}
N 1620 -440 1640 -440 {}
C {lab_pin.sym} 1640 -440 0 0 {name=lp7d lab=vdd}
C {symbols/nfet_03v3.sym} 1600 -620 0 0 {name=NINV7 model=nfet_03v3 W=2u L=0.5u nf=1 m=1}
N 1620 -650 1620 -670 {}
C {lab_pin.sym} 1620 -670 0 0 {name=lv7a lab=tb7}
N 1580 -620 1560 -620 {}
C {lab_pin.sym} 1560 -620 0 0 {name=lv7b lab=t7}
N 1620 -590 1620 -570 {}
C {lab_pin.sym} 1620 -570 0 0 {name=lv7c lab=vss}
N 1620 -620 1640 -620 {}
C {lab_pin.sym} 1640 -620 0 0 {name=lv7d lab=vss}
C {symbols/pfet_03v3.sym} 1660 -760 0 0 {name=PINV7 model=pfet_03v3 W=4u L=0.5u nf=1 m=1}
N 1680 -790 1680 -810 {}
C {lab_pin.sym} 1680 -810 0 0 {name=lw7a lab=vdd}
N 1680 -730 1680 -710 {}
C {lab_pin.sym} 1680 -710 0 0 {name=lw7b lab=tb7}
N 1640 -760 1620 -760 {}
C {lab_pin.sym} 1620 -760 0 0 {name=lw7c lab=t7}
N 1680 -760 1700 -760 {}
C {lab_pin.sym} 1700 -760 0 0 {name=lw7d lab=vdd}
C {iopin.sym} -250 500 0 0 {name=p60 lab=p}
C {iopin.sym} -250 440 0 0 {name=p61 lab=m}
C {iopin.sym} -250 380 0 0 {name=p62 lab=vss}
C {iopin.sym} -250 320 0 0 {name=p63 lab=t0}
C {iopin.sym} -250 260 0 0 {name=p64 lab=t1}
C {iopin.sym} -250 200 0 0 {name=p65 lab=t2}
C {iopin.sym} -250 140 0 0 {name=p66 lab=t3}
C {iopin.sym} -250 80 0 0 {name=p67 lab=t4}
C {iopin.sym} -250 20 0 0 {name=p68 lab=t5}
C {iopin.sym} -250 -40 0 0 {name=p69 lab=t6}
C {iopin.sym} -250 -100 0 0 {name=p70 lab=t7}
C {iopin.sym} -250 -160 0 0 {name=p71 lab=vdd}
