#!/usr/bin/env bash
# Regenerate design/netlist/*.spice from the xschem schematics (issue #6).
#
# This is the reproducible derivation step the T1 "design sources" pass
# condition requires (docs/design-evidence-tiers.md, cited from klayout-tools
# in issue #6): committed schematics + a derived netlist that is
# *regenerated on schematic change*, not a one-off manual export. Re-run
# this script any time design/*.sch changes and commit the resulting
# design/netlist/*.spice alongside the schematic edit.
#
# Usage: design/regen-netlist.sh
#
# Resolves the gf180mcu PDK the same way design/xschemrc does: PDK_ROOT (if
# already set) first, then `klt pdk find` (see docs in design/README.md),
# then the usual volare/ciel/system install locations.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DESIGN_DIR="$REPO_ROOT/design"
RCFILE="$DESIGN_DIR/xschemrc"
NETLIST_DIR="$DESIGN_DIR/netlist"

if [[ -z "${PDK_ROOT:-}" ]]; then
  if command -v klt >/dev/null 2>&1; then
    RESOLVED_ROOT="$(klt pdk find --pdk gf180mcuC --format json 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin).get("root",""))' 2>/dev/null || true)"
    if [[ -n "$RESOLVED_ROOT" ]]; then
      export PDK_ROOT="$RESOLVED_ROOT"
    fi
  fi
fi
: "${PDK_ROOT:?PDK_ROOT not set and could not be resolved via 'klt pdk find --pdk gf180mcuC'. Set PDK_ROOT to the volare/ciel install root (parent of gf180mcuC/) and re-run.}"
export PDK="${PDK:-gf180mcuC}"

MODEL_DIR="$PDK_ROOT/$PDK/libs.tech/ngspice"
if [[ ! -f "$MODEL_DIR/design.ngspice" || ! -f "$MODEL_DIR/sm141064.ngspice" ]]; then
  echo "ERROR: gf180mcu ngspice models not found under $MODEL_DIR" >&2
  echo "       Did you 'volare fetch --pdk gf180mcu <hash>' and 'volare enable ...'?" >&2
  exit 1
fi

mkdir -p "$NETLIST_DIR"

echo "== gf180-rcosc netlist regen: $(date -u +%Y-%m-%dT%H:%M:%SZ) =="
echo "PDK_ROOT=$PDK_ROOT PDK=$PDK"
echo "xschem: $(xschem --version 2>&1 | head -1)"

# Every schematic that is netlisted directly (a real entry point, not a
# hierarchical building block only ever reached via another symbol).
# rcosc_top.sch is the oscillator block itself; smoke_test.sch is the
# bring-up testbench (issue #6 non-goals: functional/DC sanity only).
ENTRY_POINTS=(rcosc_top smoke_test)

for name in "${ENTRY_POINTS[@]}"; do
  sch="$DESIGN_DIR/$name.sch"
  if [[ ! -f "$sch" ]]; then
    echo "ERROR: expected schematic not found: $sch" >&2
    exit 1
  fi
  echo "-- netlisting $name.sch --"
  xschem -n -x -q -r --rcfile "$RCFILE" -o "$NETLIST_DIR" "$sch"
  if [[ ! -f "$NETLIST_DIR/$name.spice" ]]; then
    echo "ERROR: netlist not produced at $NETLIST_DIR/$name.spice" >&2
    exit 1
  fi
done

# pdk_include.spice: the model-library recipe smoke_test.spice's
# `.include pdk_include.spice` line pulls in. Generated here (not
# hardcoded in the schematic, so smoke_test.sch has no machine-specific
# path) -- overwritten each run by design, not evidence itself.
#
# Recipe notes (see issue #6 PR description for the debugging trail):
#   - `.lib <file> typical`       activates the nfet_03v3/pfet_03v3 device
#                                  subckts (nested inside gf180mcu's own
#                                  'fets_mm' library section) plus their
#                                  typical-corner model parameters.
#   - `.lib <file> res_typical`   sets rsh_* sheet-resistance parameters and
#                                  activates the 'res' library section that
#                                  defines ppolyf_u_1k (and siblings).
#   - `.lib <file> mimcap_typical` sets the mim_corner_* parameters the MIM
#                                  cap subckts below use.
#   - `.lib <file> cap_mim`        defines cap_mim_1f0fF (and cap_mim_1f5fF /
#                                  cap_mim_2f0fF) -- the LEGACY/local model
#                                  set xschem's cap_mim_*.sym symbols use, as
#                                  distinct from the "cap_mim_new" /
#                                  *_m2m3_noshield-style subckts in
#                                  sm141064_mim.ngspice, which model a
#                                  different (metal-stack-specific) device.
#   A blanket `.include sm141064.ngspice` was deliberately NOT used: it
#   parses every top-level `.LIB ... .ENDL` block unconditionally, which
#   redefines several subckts (nfet_03v3, ppolyf_u_1k, ...) once per corner
#   block and produced spurious "too few parameters" subcircuit-expansion
#   errors -- always resolve gf180mcu devices via targeted `.lib` calls.
cat > "$NETLIST_DIR/pdk_include.spice" <<EOF
* Generated by design/regen-netlist.sh from \$PDK_ROOT/\$PDK -- do not edit
* by hand; re-run design/regen-netlist.sh to refresh.
.include $MODEL_DIR/design.ngspice
.lib $MODEL_DIR/sm141064.ngspice typical
.lib $MODEL_DIR/sm141064.ngspice res_typical
.lib $MODEL_DIR/sm141064.ngspice mimcap_typical
.lib $MODEL_DIR/sm141064.ngspice cap_mim
EOF

echo "== netlist regen complete: $NETLIST_DIR =="
