#!/usr/bin/env python3
"""gf180-rcosc comparator/latch delay-probe instrumentation campaign (issue #51).

Instrumentation pass, not a spec-row campaign: this driver re-uses the
``pvt_sweep.py`` deck composition but replaces the measurement with a
node-crossing decomposition of steady-state oscillation cycles, quantifying
the per-stage propagation delays DR-0003's post-trim arithmetic never
budgeted and DR-0012/DR-0014 attributed the remaining post-trim residual to:

  t_cmp_h  vc crossing vh  ->  cmph_out crossing mid-rail   (comparator, high side)
  t_lat_h  cmph_out        ->  clk rising                   (NOR-NOR latch set path)
  t_cmp_l  vc falling through vl -> cmpl_out crossing mid   (comparator, low side)
  t_lat_l  cmpl_out        ->  clk falling                  (latch reset path)
  charge   clk falling     ->  next vc crossing of vh       (the RC term, 0 -> vh)
  dsum     t_cmp_h + t_lat_h + t_cmp_l + t_lat_l            (delay paid into
                                                              the period per cycle)
  overshoot_v  max(vc) - vh                                 (the symptom of the
                                                              high-side delay, not
                                                              itself a period cost:
                                                              MDISCH resets vc to ~0)

Methodology: the transient (``tran 100p`` -- 2x finer than the campaign's
200p, for edge-resolution on the fast discharge flank) is dumped with
``wrdata`` and every crossing is extracted by linear interpolation in Python,
then events are aligned into cycles by timestamp proximity.  Edge *index*
matching (``meas ... rise=N`` across different nodes) is deliberately not
used: nodes accumulate different glitch counts during startup, which desyncs
their indices by whole cycles (observed on the ss/-40C/3.0V/0xCF cell during
this driver's own bring-up).  Several steady-state cycles are decomposed and
the per-cycle spread is reported, so a single misaligned cycle cannot pass
silently.

The point set is the two per-corner calibrated-code sets of a prior full
campaign (surrogate- and ratified-target calibration, read from that
campaign's manifest) across the same 7-process x 3-temperature x 3-supply
factorial, plus a code sweep at ``ss``/27 C that reproduces DR-0014's
per-code supply-sensitivity pairing (0x80 / 0x9D / 0xCF / 0xEF) so the
stage decomposition can be compared directly against the code-monotonicity
attribution in that record.

Evidence is append-only, same convention as ``pvt_sweep.py``:

  sim/pvt/corners/<runid>/<key>.log     per-point analysis: aligned-cycle event
                                        timestamps, derived stage delays,
                                        cross-cycle stability
  sim/pvt/results/<runid>/results.csv   one row per simulated point
  sim/pvt/results/<runid>/manifest.json provenance + probe configuration
  sim/pvt/results/<runid>/summary.md    stage-delay tables + the supply / delta-T
                                        sensitivity decomposition
"""

from __future__ import annotations

import argparse
import concurrent.futures
import csv
import json
import os
import re
import subprocess
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pvt_sweep import (  # noqa: E402
    MEAS_FIRST_EDGE,
    NETLIST,
    PROCESS_CORNERS,
    REPO_ROOT,
    SIM_PVT,
    TSTOP_NS_DEFAULT,
    TSTOP_NS_RETRY,
    Point,
    corner_include,
    git_dirty,
    git_sha,
    resolve_pdk,
    tool_version,
)

TEMPS_C = [-40.0, 27.0, 85.0]
VDDS_V = [3.0, 3.3, 3.6]

# Transient output step: 100 ps, half the campaign's 200 ps, so the fast
# discharge flank of vc (~100 ps) is sampled by >=2 points for the
# interpolated vl-crossing extraction.
TSTEP = "100p"

# Candidate steady-state cycles to decompose (rising clk edges well past the
# campaign's 5-edge startup skip).  All candidates are analyzed; the reported
# point is their median, with the spread recorded.
CYCLE_EDGES = [MEAS_FIRST_EDGE + 5 + i for i in range(3)]

# wrdata column order (each vector contributes a time, value pair).
WDATA_NODES = ["vc", "vh", "vl", "cmph_out", "cmpl_out", "clk", "vdd"]

# DR-0014's per-code supply-sensitivity pairing at ss/27C (switchprobe
# continuity): the codes whose frozen-map in-chain trim mass DR-0014's supply
# rows grow monotonically against.
CODESWEEP_PROCESS = "ss"
CODESWEEP_TEMP_C = 27.0
CODESWEEP_CODES = [0x80, 0x9D, 0xCF, 0xEF]


def probe_control(tstop_ns: int) -> str:
    vectors = " ".join(
        n if n in ("clk", "vdd") else f"v(xxdut.{n})" for n in WDATA_NODES
    )
    return (
        "* pvt_control.spice -- GENERATED by sim/pvt/delay_probe.py, do not edit.\n"
        ".control\n"
        "set noaskquit\n"
        f"tran {TSTEP} {tstop_ns}n\n"
        f"wrdata probe.txt {vectors}\n"
        "quit\n"
        ".endc\n"
    )


@dataclass(frozen=True)
class ProbePoint(Point):
    """One instrumented operating point, tagged with its calibration basis."""

    basis: str = "surrogate"  # surrogate | ratified | codesweep

    @property
    def key(self) -> str:
        return (
            f"{self.basis}_{self.process}_T{int(self.temp_c):+04d}C_V{self.vdd_v:.1f}".replace(
                ".", "p"
            )
            + f"_code0x{self.code:02X}"
        )


DERIVED = [
    "period",
    "t_cmp_h",
    "t_lat_h",
    "t_fall",
    "t_cmp_l",
    "t_lat_l",
    "charge",
    "dsum",
    "overshoot_v",
    "vh_dc",
    "vl_dc",
    "fosc",
]


def _crossings(ts: list[float], v: list[float], level: float, rising: bool) -> list[float]:
    out = []
    for k in range(len(ts) - 1):
        a, b = v[k], v[k + 1]
        if rising and a < level <= b:
            out.append(ts[k] + (level - a) / (b - a) * (ts[k + 1] - ts[k]))
        elif not rising and a > level >= b:
            out.append(ts[k] + (a - level) / (a - b) * (ts[k + 1] - ts[k]))
    return out


def _first_after(times: list[float], t: float) -> float | None:
    for x in times:
        if x >= t:
            return x
    return None


def _last_before(times: list[float], t: float) -> float | None:
    for x in reversed(times):
        if x <= t:
            return x
    return None


def analyze(wdata_path: Path) -> tuple[dict[str, float], str]:
    """Parse the wrdata dump and decompose the candidate cycles.

    Returns (median derived values, diagnostic text).  Raises on unusable data.
    """
    series: dict[str, tuple[list[float], list[float]]] = {n: ([], []) for n in WDATA_NODES}
    with wdata_path.open() as fh:
        for line in fh:
            parts = line.split()
            if len(parts) != 2 * len(WDATA_NODES):
                continue
            try:
                nums = [float(x) for x in parts]
            except ValueError:
                continue
            for i, name in enumerate(WDATA_NODES):
                series[name][0].append(nums[2 * i])
                series[name][1].append(nums[2 * i + 1])

    ts_vc, v_vc = series["vc"]
    ts_vh, v_vh = series["vh"]
    ts_vl, v_vl = series["vl"]
    _, v_vdd = series["vdd"]
    if not ts_vc or not v_vdd:
        raise RuntimeError("empty wrdata dump")
    vdd = v_vdd[len(v_vdd) // 2]
    vmid = vdd / 2.0

    # Threshold references: mean of each divider node over the last half of
    # the window (quasi-DC; excludes startup).
    t_mid = ts_vh[len(ts_vh) // 2]
    vh = sum(x for t, x in zip(ts_vh, v_vh) if t >= t_mid) / max(
        1, sum(1 for t in ts_vh if t >= t_mid)
    )
    vl = sum(x for t, x in zip(ts_vl, v_vl) if t >= t_mid) / max(
        1, sum(1 for t in ts_vl if t >= t_mid)
    )

    t_clk_r = _crossings(*series["clk"], vmid, True)
    t_clk_f = _crossings(*series["clk"], vmid, False)
    t_vh_r = _crossings(ts_vc, v_vc, vh, True)
    t_vl_f = _crossings(ts_vc, v_vc, vl, False)
    t_cmph = _crossings(*series["cmph_out"], vmid, True)
    t_cmpl = _crossings(*series["cmpl_out"], vmid, True)
    if len(t_clk_r) < CYCLE_EDGES[-1] + 2:
        raise RuntimeError(f"only {len(t_clk_r)} clk rising crossings in window")

    cycles: list[dict[str, float]] = []
    notes = []
    for edge in CYCLE_EDGES:
        tr = t_clk_r[edge]
        t_cmph_c = _last_before(t_cmph, tr)
        t_vh_c = _last_before(t_vh_r, tr)
        t_clkf = _first_after(t_clk_f, tr)
        t_vlf = _first_after(t_vl_f, tr)
        t_cmpl_c = _first_after(t_cmpl, tr)
        t_vh_next = _first_after(t_vh_r, t_clkf) if t_clkf else None
        tr_next = _first_after(t_clk_r, t_clkf) if t_clkf else None
        if None in (t_cmph_c, t_vh_c, t_clkf, t_vlf, t_cmpl_c, t_vh_next, tr_next):
            notes.append(f"edge {edge}: incomplete event set, skipped")
            continue
        assert t_cmph_c and t_vh_c and t_clkf and t_vlf and t_cmpl_c and t_vh_next and tr_next
        period = tr_next - tr
        d = {
            "period": period,
            "t_cmp_h": t_cmph_c - t_vh_c,
            "t_lat_h": tr - t_cmph_c,
            "t_fall": t_vlf - tr,
            "t_cmp_l": t_cmpl_c - t_vlf,
            "t_lat_l": t_clkf - t_cmpl_c,
            "charge": t_vh_next - t_clkf,
        }
        d["dsum"] = d["t_cmp_h"] + d["t_lat_h"] + d["t_cmp_l"] + d["t_lat_l"]
        bad = [
            k
            for k, x in d.items()
            if not (0.0 < x < period if k != "period" else x > 0.0)
        ]
        if bad:
            notes.append(f"edge {edge}: out-of-cycle {bad}, skipped")
            continue
        # overshoot: peak of vc between this cycle's vh crossing and the
        # following discharge turn-on (clk rise), plus MDISCH's turn-off tail.
        pk = max(
            x for t, x in zip(ts_vc, v_vc) if t_vh_c <= t <= tr + 2e-9
        )
        d["overshoot_v"] = pk - vh
        d["vh_dc"] = vh
        d["vl_dc"] = vl
        d["fosc"] = 1.0 / period
        cycles.append(d)

    if not cycles:
        raise RuntimeError("no consistent cycle found: " + "; ".join(notes))

    out: dict[str, float] = {}
    for k in cycles[0]:
        vals = sorted(c[k] for c in cycles)
        out[k] = vals[len(vals) // 2]
    spread = {
        k: max(c[k] for c in cycles) - min(c[k] for c in cycles) for k in cycles[0]
    }
    diag_lines = [
        f"vdd={vdd:.4f} vmid={vmid:.4f} vh={vh:.6f} vl={vl:.6f}",
        f"crossing counts: clk_r={len(t_clk_r)} clk_f={len(t_clk_f)} "
        f"vh_r={len(t_vh_r)} vl_f={len(t_vl_f)} cmph={len(t_cmph)} cmpl={len(t_cmpl)}",
        f"cycles decomposed: {len(cycles)} / {len(CYCLE_EDGES)} candidates",
    ]
    diag_lines += [f"note: {n}" for n in notes]
    diag_lines.append(
        "cross-cycle spread (max-min): "
        + " ".join(f"{k}={spread[k] * 1e9:.4f}ns" for k in DERIVED if k in spread)
        if spread
        else "cross-cycle spread: n/a"
    )
    diag_lines.append(
        "median decomposition: "
        + " ".join(
            f"{k}={out[k] * 1e9:.4f}ns" if k not in ("fosc", "vh_dc", "vl_dc", "overshoot_v") else (
                f"{k}={out[k] * 1e6:.4f}MHz" if k == "fosc" else f"{k}={out[k]:.6f}V"
            )
            for k in DERIVED
            if k in out
        )
    )
    return out, "\n".join(diag_lines)


@dataclass
class ProbeResult:
    point: ProbePoint
    values: dict[str, float]
    status: str
    log_path: str
    tstop_ns: int
    seconds: float = 0.0
    stderr_tail: str = ""


@dataclass
class Probe:
    runid: str
    model_dir: Path
    log_dir: Path
    build_dir: Path
    jobs: int
    results: list[ProbeResult] = field(default_factory=list)


def run_probe(pr: Probe, netlist_text: str, point: ProbePoint) -> ProbeResult:
    tstop = TSTOP_NS_DEFAULT
    last: ProbeResult | None = None
    for attempt in (1, 2):
        rundir = pr.build_dir / point.key / f"t{tstop}"
        rundir.mkdir(parents=True, exist_ok=True)
        corner = corner_include(pr.model_dir, point)
        control = probe_control(tstop)
        deck = netlist_text
        for token, body in (
            (".include pvt_corner.spice", corner),
            (".include pvt_control.spice", control),
        ):
            if token not in deck:
                sys.exit(f"ERROR: '{token}' not found in {NETLIST}")
            deck = deck.replace(token, body, 1)
        (rundir / "run.spice").write_text(deck)
        started = time.time()
        proc = subprocess.run(
            ["ngspice", "-b", "run.spice"],
            cwd=rundir,
            capture_output=True,
            text=True,
            timeout=1800,
        )
        elapsed = time.time() - started
        out = (proc.stdout or "") + "\n" + (proc.stderr or "")
        log_rel = f"sim/pvt/corners/{pr.runid}/{point.key}.log"
        header = (
            "====================================================================\n"
            f"gf180-rcosc delay-probe run: {point.key}\n"
            f"run id      : {pr.runid}\n"
            f"basis       : {point.basis}\n"
            f"process     : {point.process} "
            f"(fets={PROCESS_CORNERS[point.process][0]} "
            f"res={PROCESS_CORNERS[point.process][1]} "
            f"mimcap={PROCESS_CORNERS[point.process][2]})\n"
            f"temperature : {point.temp_c:g} C\n"
            f"supply      : {point.vdd_v:g} V\n"
            f"trim code   : 0x{point.code:02X} ({point.code})\n"
            f"transient   : tran {TSTEP} {tstop}n, wrdata + Python crossing/"
            "cycle-alignment analysis (see driver docstring)\n"
            f"wall clock  : {elapsed:.1f} s\n"
            f"exit status : {proc.returncode}\n"
            "====================================================================\n"
        )
        wdata = rundir / "probe.txt"
        values: dict[str, float] = {}
        diag = ""
        try:
            if not wdata.is_file():
                raise RuntimeError("no probe.txt written")
            values, diag = analyze(wdata)
            status = "ok"
        except Exception as exc:  # analysis failure -> retry at longer tstop
            diag = f"analysis error: {exc}"
            status = f"analysis-failed"
        (pr.log_dir / f"{point.key}.log").write_text(
            header + diag + "\n" + out[-2000:]
        )
        if status == "ok":
            return ProbeResult(point, values, status, log_rel, tstop, elapsed)
        last = ProbeResult(
            point,
            values,
            status,
            log_rel,
            tstop,
            elapsed,
            stderr_tail="\n".join(out.strip().splitlines()[-6:]),
        )
        if attempt == 1:
            tstop = TSTOP_NS_RETRY
    assert last is not None
    return last


def read_cal_codes(cal_dir: Path) -> dict[str, dict[str, int]]:
    """Read the per-corner calibrated trim codes from a prior campaign manifest."""
    manifest = json.loads((cal_dir / "manifest.json").read_text())
    out: dict[str, dict[str, int]] = {}
    for key, basis in (
        ("calibration_spec_target", "ratified"),
        ("calibration_surrogate_target", "surrogate"),
    ):
        entry = manifest.get(key)
        if not entry:
            continue
        codes: dict[str, int] = {}
        for proc, info in entry.items():
            if isinstance(info, dict) and "code" in info:
                codes[proc] = int(info["code"])
        if codes:
            out[basis] = codes
    if not out:
        sys.exit(f"ERROR: no calibration tables found in {cal_dir / 'manifest.json'}")
    return out


def ns(x: float | None) -> str:
    return f"{x * 1e9:.4f}" if x is not None else ""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--cal-from",
        type=Path,
        default=None,
        help="prior campaign results dir to read per-corner calibrated codes from "
        "(default: newest sim/pvt/results/*/ with a calibration manifest)",
    )
    ap.add_argument("--jobs", type=int, default=min(12, (os.cpu_count() or 8)))
    ap.add_argument("--keep-build", action="store_true", help="keep generated decks")
    args = ap.parse_args()

    cal_dir = args.cal_from
    if cal_dir is None:
        candidates = sorted(
            (d for d in (SIM_PVT / "results").iterdir() if (d / "manifest.json").is_file()),
            key=lambda d: d.name,
        )
        if not candidates:
            sys.exit("ERROR: no prior campaign results found; pass --cal-from")
        cal_dir = candidates[-1]
    cal_codes = read_cal_codes(cal_dir)
    print(f"calibrated codes read from: {cal_dir}")
    for basis, codes in cal_codes.items():
        pretty = " ".join(f"{p}=0x{c:02X}" for p, c in codes.items())
        print(f"  {basis}: {pretty}")

    points: list[ProbePoint] = []
    for basis, codes in cal_codes.items():
        for proc, code in codes.items():
            for temp in TEMPS_C:
                for vdd in VDDS_V:
                    points.append(ProbePoint(proc, temp, vdd, code, basis))
    for code in CODESWEEP_CODES:
        for vdd in VDDS_V:
            points.append(
                ProbePoint(CODESWEEP_PROCESS, CODESWEEP_TEMP_C, vdd, code, "codesweep")
            )
    # de-duplicate (a codesweep code can coincide with a calibrated code cell)
    points = list(dict.fromkeys(points))

    runid = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    pdk_root, pdk, model_dir = resolve_pdk()
    log_dir = SIM_PVT / "corners" / runid
    results_dir = SIM_PVT / "results" / runid
    build_dir = REPO_ROOT / "sim" / "build" / f"delayprobe-{runid}"
    for d in (log_dir, results_dir, build_dir):
        if d.exists() and any(d.iterdir()):
            sys.exit(f"ERROR: {d} already exists and is non-empty (append-only)")
        d.mkdir(parents=True, exist_ok=True)

    netlist_text = Path(NETLIST).read_text()
    probe = Probe(runid, model_dir, log_dir, build_dir, args.jobs)

    print(f"== delay probe: {len(points)} points, {args.jobs} parallel jobs ==")
    started = time.time()
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        futures = {pool.submit(run_probe, probe, netlist_text, p): p for p in points}
        done = 0
        for fut in concurrent.futures.as_completed(futures):
            res = fut.result()
            probe.results.append(res)
            done += 1
            if res.status == "ok":
                v = res.values
                fmt = (
                    f"T={v['period'] * 1e9:7.3f}ns dsum={v['dsum'] * 1e9:6.3f}ns "
                    f"(h:{v['t_cmp_h'] * 1e9:.2f}+{v['t_lat_h'] * 1e9:.2f} "
                    f"l:{v['t_cmp_l'] * 1e9:.2f}+{v['t_lat_l'] * 1e9:.2f})"
                )
            else:
                fmt = res.status
            print(f"  [{done:3d}/{len(points):3d}] {res.point.key:<40} {fmt}", flush=True)
    wall = time.time() - started

    # -- results.csv ------------------------------------------------------
    csv_path = results_dir / "results.csv"
    cols = [
        "basis",
        "process",
        "temp_c",
        "vdd_v",
        "trim_code",
        "trim_hex",
        "status",
        "f_mhz",
        "period_ns",
        "vh_v",
        "vl_v",
        "t_cmp_h_ns",
        "t_lat_h_ns",
        "t_cmp_l_ns",
        "t_lat_l_ns",
        "t_fall_ns",
        "charge_ns",
        "dsum_ns",
        "overshoot_mv",
        "tstop_ns",
        "seconds",
        "log",
    ]
    with csv_path.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(cols)
        for res in sorted(
            probe.results,
            key=lambda r: (r.point.basis, r.point.process, r.point.temp_c, r.point.vdd_v, r.point.code),
        ):
            v = res.values
            w.writerow(
                [
                    res.point.basis,
                    res.point.process,
                    f"{res.point.temp_c:g}",
                    f"{res.point.vdd_v:g}",
                    res.point.code,
                    f"0x{res.point.code:02X}",
                    res.status,
                    f"{v['fosc'] / 1e6:.6f}" if "fosc" in v else "",
                    ns(v.get("period")),
                    f"{v.get('vh_dc', float('nan')):.6f}" if "vh_dc" in v else "",
                    f"{v.get('vl_dc', float('nan')):.6f}" if "vl_dc" in v else "",
                    ns(v.get("t_cmp_h")),
                    ns(v.get("t_lat_h")),
                    ns(v.get("t_cmp_l")),
                    ns(v.get("t_lat_l")),
                    ns(v.get("t_fall")),
                    ns(v.get("charge")),
                    ns(v.get("dsum")),
                    f"{v.get('overshoot_v', float('nan')) * 1e3:.2f}"
                    if "overshoot_v" in v
                    else "",
                    res.tstop_ns,
                    f"{res.seconds:.1f}",
                    res.log_path,
                ]
            )

    # -- manifest.json ----------------------------------------------------
    manifest = {
        "runid": runid,
        "utc": datetime.now(timezone.utc).isoformat(),
        "driver": "sim/pvt/delay_probe.py",
        "git_sha": git_sha(),
        "git_dirty": git_dirty(),
        "host_arch": subprocess.run(
            ["uname", "-m"], capture_output=True, text=True
        ).stdout.strip()
        or "unknown",
        "ngspice": tool_version(["ngspice", "-v"]),
        "pdk_root": str(pdk_root),
        "pdk": pdk,
        "model_dir": str(model_dir),
        "netlist": str(NETLIST),
        "cal_codes_from": str(cal_dir),
        "calibration_codes": cal_codes,
        "tran_step": TSTEP,
        "cycle_edges": CYCLE_EDGES,
        "tstop_ns_default": TSTOP_NS_DEFAULT,
        "tstop_ns_retry": TSTOP_NS_RETRY,
        "codesweep": {
            "process": CODESWEEP_PROCESS,
            "temp_c": CODESWEEP_TEMP_C,
            "codes": [f"0x{c:02X}" for c in CODESWEEP_CODES],
        },
        "points": len(points),
        "ok": sum(1 for r in probe.results if r.status == "ok"),
        "failed": sum(1 for r in probe.results if r.status != "ok"),
        "wall_clock_s": round(wall, 1),
        "jobs": args.jobs,
    }
    (results_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")

    # -- summary.md (mechanical tables; analysis lives in the DR) ---------
    def get(res_list, basis, proc, temp, vdd, code=None):
        for r in res_list:
            if (
                r.point.basis == basis
                and r.point.process == proc
                and r.point.temp_c == temp
                and r.point.vdd_v == vdd
                and (code is None or r.point.code == code)
                and r.status == "ok"
            ):
                return r.values
        return None

    lines = [
        f"# Delay-probe instrumentation {runid}",
        "",
        f"Driver: `sim/pvt/delay_probe.py` against `{NETLIST}` (schematic-unchanged",
        f"reproduction basis; calibrated codes read from `{cal_dir}`).",
        f"{manifest['ok']} ok / {manifest['failed']} failed points, "
        f"{wall:.1f}s wall clock at {args.jobs} jobs.",
        "",
        "Stage-delay decomposition of steady-state cycles (median of the",
        f"decomposed candidates, edges {CYCLE_EDGES[0]}..{CYCLE_EDGES[-1]}): all",
        "cells ns; `dsum` = t_cmp_h + t_lat_h + t_cmp_l + t_lat_l is the",
        "comparator/latch delay paid into the period per cycle.",
        "",
    ]
    for basis, codes in cal_codes.items():
        lines += [
            f"## Calibrated-code set: {basis} target",
            "",
            "### Per-stage delays and dsum (27 C)",
            "",
            "| proc | code | VDD | period | t_cmp_h | t_lat_h | t_cmp_l | t_lat_l | dsum | charge | overshoot (mV) |",
            "|---|---|---|---|---|---|---|---|---|---|---|",
        ]
        for proc, code in codes.items():
            for vdd in VDDS_V:
                v = get(probe.results, basis, proc, 27.0, vdd)
                if v is None:
                    lines.append(f"| {proc} | 0x{code:02X} | {vdd:g} | (failed) | | | | | | | |")
                    continue
                lines.append(
                    f"| {proc} | 0x{code:02X} | {vdd:g} | {ns(v['period'])} "
                    f"| {ns(v['t_cmp_h'])} | {ns(v['t_lat_h'])} "
                    f"| {ns(v['t_cmp_l'])} | {ns(v['t_lat_l'])} "
                    f"| {ns(v['dsum'])} | {ns(v['charge'])} "
                    f"| {v['overshoot_v'] * 1e3:.1f} |"
                )
        lines += [
            "",
            "### Supply decomposition at 27 C (span 3.0 -> 3.6 V, same corner/code)",
            "",
            "| proc | dPeriod (ns) | dDsum (ns) | dCharge (ns) | delay share of dPeriod |",
            "|---|---|---|---|---|",
        ]
        for proc, code in codes.items():
            v3, v36 = (
                get(probe.results, basis, proc, 27.0, 3.0),
                get(probe.results, basis, proc, 27.0, 3.6),
            )
            if v3 is None or v36 is None:
                lines.append(f"| {proc} | (failed) | | | |")
                continue
            dper = (v3["period"] - v36["period"]) * 1e9
            dsum = (v3["dsum"] - v36["dsum"]) * 1e9
            dchg = (v3["charge"] - v36["charge"]) * 1e9
            share = f"{dsum / dper * 100:.1f}%" if abs(dper) > 1e-6 else "n/a"
            lines.append(f"| {proc} | {dper:+.4f} | {dsum:+.4f} | {dchg:+.4f} | {share} |")
        lines += [
            "",
            "### dsum vs temperature at 3.3 V (per-corner calibrated code)",
            "",
            "| proc | dsum(-40C) | dsum(27C) | dsum(85C) | ppm/K of dsum (cold leg) | dsum share of period (27C) |",
            "|---|---|---|---|---|---|",
        ]
        for proc, code in codes.items():
            vc, vn, vh = (
                get(probe.results, basis, proc, -40.0, 3.3),
                get(probe.results, basis, proc, 27.0, 3.3),
                get(probe.results, basis, proc, 85.0, 3.3),
            )
            if None in (vc, vn, vh):
                lines.append(f"| {proc} | (failed) | | | | |")
                continue
            ppm = (vc["dsum"] - vn["dsum"]) / vn["dsum"] / (-40.0 - 27.0) * 1e6
            share = vn["dsum"] / vn["period"] * 100
            lines.append(
                f"| {proc} | {ns(vc['dsum'])} | {ns(vn['dsum'])} | {ns(vh['dsum'])} "
                f"| {ppm:+.0f} | {share:.1f}% |"
            )
        lines.append("")
    lines += [
        "## Code sweep at ss / 27 C (DR-0014 switchprobe continuity)",
        "",
        "| code | VDD | period | dsum | charge | delay share |",
        "|---|---|---|---|---|---|",
    ]
    for code in CODESWEEP_CODES:
        for vdd in VDDS_V:
            v = get(
                probe.results,
                "codesweep",
                CODESWEEP_PROCESS,
                CODESWEEP_TEMP_C,
                vdd,
                code,
            )
            if v is None:
                lines.append(f"| 0x{code:02X} | {vdd:g} | (failed) | | | |")
                continue
            share = v["dsum"] / v["period"] * 100
            lines.append(
                f"| 0x{code:02X} | {vdd:g} | {ns(v['period'])} | {ns(v['dsum'])} "
                f"| {ns(v['charge'])} | {share:.1f}% |"
            )
    lines.append("")
    (results_dir / "summary.md").write_text("\n".join(lines))

    if not args.keep_build:
        subprocess.run(["rm", "-rf", str(build_dir)], check=False)

    print(
        f"== delay probe done: {manifest['ok']} ok / {manifest['failed']} failed, "
        f"{wall:.1f}s -> sim/pvt/results/{runid}/ =="
    )
    return 0 if manifest["failed"] == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
