#!/usr/bin/env python3
"""Generate the `klt pex` testbench requests for rcosc_top (issue #70).

One request per VDD (3.0 / 3.3 / 3.6 V) because the frequency `.meas` card
needs the VDD/2 threshold at authoring time and `klt sim`'s supply axis can
only `alter` a source.  Each request carries the process (tt/ff/ss bundles,
the same `.lib` sections `sim/pvt/pvt_sweep.py` uses) x temperature
(-40/27/85 C) grid = 9 corners, so the three requests are the same 27-point
corner-endpoint subset `pex_pvt_sweep.py` covers.  Trim code is the fixed
post-#60 calibration code 0xA3 (the code the schematic campaign
sim/pvt/results/20260923T030125Z calibrated tt to), held at every point.

Row coverage: the single frequency figure (fosc, measured over 20 periods
after skipping 5 edges, identical to pvt_control.spice).  No `limits` are
declared: the ratified accuracy rows are post-trim percentages vs a
calibrated reference, not absolute per-corner limits, so this report records
the schematic-vs-extracted delta and does not grade rows.

Run from this directory:  python3 gen_requests.py
"""
import json
from pathlib import Path

CODE = 0xA3
VDDS = [3.0, 3.3, 3.6]
TEMPS = [-40, 27, 85]
PROC = {
    "tt": ["typical", "res_typical", "mimcap_typical", "cap_mim"],
    "ff": ["ff", "res_ff", "mimcap_ff", "cap_mim"],
    "ss": ["ss", "res_ss", "mimcap_ss", "cap_mim"],
}
here = Path(__file__).parent
SRC = here.parent.parent.parent / "design" / "netlist" / "pvt_tb.spice"

# Schematic-side DUT.  The schematic DUT is the `.subckt rcosc_top ... .ends`
# hierarchy that pvt_tb.spice embeds (the exact netlist sim/pvt/ simulates).
# `klt extract` writes its header in alphabetical pin order (clk t0..t7 vdd
# vss) and `klt pex` swaps only the testbench's one `.include`, so the
# testbench's positional instance line must use that order on BOTH sides.  The
# schematic subckt's own pin order is vdd vss clk t0..t7, so the wrapper below
# renames it `rcosc_top_core` and declares `rcosc_top` in the extracted
# (alphabetical) order around it.  No device or connection is edited.
text = SRC.read_text().splitlines()
start = next(i for i, l in enumerate(text) if "expanding" in l and "rcosc_top.sym" in l)
end = next(i for i, l in enumerate(text) if l.strip() == ".end")
block = [l for l in text[start:end] if not l.startswith(("** sym_path:", "** sch_path:"))]
hdr = next(i for i, l in enumerate(block) if l.lower().startswith(".subckt rcosc_top "))
assert block[hdr].split()[2:] == "vdd vss clk t0 t1 t2 t3 t4 t5 t6 t7".split(), block[hdr]
block[hdr] = ".subckt rcosc_top_core vdd vss clk t0 t1 t2 t3 t4 t5 t6 t7"
wrapper = [
    "",
    "* pin-order wrapper (generated by gen_requests.py): alphabetical order, as klt extract writes it",
    ".subckt rcosc_top clk t0 t1 t2 t3 t4 t5 t6 t7 vdd vss",
    "Xcore vdd vss clk t0 t1 t2 t3 t4 t5 t6 t7 rcosc_top_core",
    ".ends rcosc_top",
]
(here / "rcosc_top_schematic.spice").write_text(
    "* schematic DUT for klt pex: pvt_tb.spice's embedded rcosc_top hierarchy + pin-order wrapper\n"
    + "\n".join(block + wrapper) + "\n"
)
for vdd in VDDS:
    tag = f"v{int(round(vdd * 10)):02d}"
    lines = [
        f"* rcosc_top klt-pex testbench, VDD={vdd:g} V, trim code 0x{CODE:02X} (generated by gen_requests.py)",
        ".param sw_stat_global=0 sw_stat_mismatch=0 mc_skew=3 res_mc_skew=3 cap_mc_skew=3 fnoicor=0",
        '.include "rcosc_top_schematic.spice"',
        "XXDUT clk t0 t1 t2 t3 t4 t5 t6 t7 vdd 0 rcosc_top",
        f"VDD vdd 0 DC {vdd:g}",
    ]
    for i in range(8):
        lines.append(f"VT{i} t{i} 0 DC {vdd * ((CODE >> i) & 1):g}")
    (here / f"tb_{tag}.spice").write_text("\n".join(lines) + "\n")
    req = {
        "netlist": f"tb_{tag}.spice",
        "engine": "ngspice",
        "netlist_source": "schematic",
        "models": {"pdk": "gf180mcuC", "lib": "libs.tech/ngspice/sm141064.ngspice"},
        "corners": {
            "process": [{"name": n, "sections": s} for n, s in PROC.items()],
            "temperature_c": TEMPS,
        },
        "analysis": {"kind": "tran", "args": "200p 1200n"},
        "measurements": [
            {"name": "ta", "spice": f".meas tran ta WHEN v(clk)={vdd / 2:.4f} RISE=5", "unit": "s"},
            {"name": "tb", "spice": f".meas tran tb WHEN v(clk)={vdd / 2:.4f} RISE=25", "unit": "s"},
            {"name": "fosc", "spice": ".meas tran fosc PARAM='20/(tb-ta)'", "unit": "Hz"},
        ],
        "batch": {"capacity_wait_s": 1200},
        "options": {"timeout_s": 600, "keep_artifacts": True,
                    "ngspice_init": ["set measureprec=8"]},
    }
    (here / f"request_{tag}.json").write_text(json.dumps(req, indent=2) + "\n")
